// ...bestaande creators...
export type CreatorBadge = 'VERIFIED' | 'PRO' | 'ELITE' | 'COACH';

export interface CommunityCreator {
  id: string;
  name: string;
  specialty: string;
  badge: CreatorBadge;
  image: string;
  followers: number;
  posts: number;
  bio: string;
  headerImage?: string; // NIEUW veld voor headerafbeelding
}

export const COMMUNITY_CREATORS: CommunityCreator[] = [
  {
    id: 'sylvana-ijsselmuiden',
    name: 'Sylvana Ijsselmuiden',
    specialty: '',
    image: '',
    followers: 0,
    posts: 0,
    bio: '',
    headerImage: '',
    socials: {
      instagram: 'https://instagram.com/sylvana',
    },
  },
  {
    id: 'dag-een',
    name: 'Dag Een',
    specialty: '',
    image: '',
    followers: 0,
    posts: 0,
    bio: '',
    headerImage: '',
    socials: {
      instagram: 'https://instagram.com/dageen.nl',
    },
  },
  {
    id: 'fierce-tobe',
    name: 'Fierce Tobe',
    specialty: '',
    image: '',
    followers: 0,
    posts: 0,
    bio: '',
    headerImage: '',
    socials: {
      instagram: 'https://instagram.com/fiercetobe',
    },
  },
  {
    id: 'tim-hofman',
    name: 'Tim Hofman',
    specialty: 'Fitness & Media',
    badge: 'VERIFIED',
    image: '',
    followers: 0,
    posts: 0,
    bio: '',
    headerImage: '',
    specialty: '',
  },
  {
    id: 'donny-roelvink',
    name: 'Donny Roelvink',
    specialty: 'Fitness & Lifestyle',
    badge: 'PRO',
    image: '',
    followers: 0,
    posts: 0,
    bio: '',
    headerImage: '',
    specialty: '',
  },
  {
    id: 'marijn-kuipers',
    name: 'Marijn Kuipers',
    specialty: 'Bodybuilding',
    badge: 'ELITE',
    image: '',
    followers: 0,
    posts: 0,
    bio: '',
    headerImage: '',
    specialty: '',
  },
  {
    id: 'elise-janssen',
    name: 'Elise Janssen',
    specialty: 'Yoga & Mindfulness',
    badge: 'COACH',
    image: '',
    followers: 0,
    posts: 0,
    bio: '',
    headerImage: '',
    specialty: '',
  },
  {
    id: 'broodje-dunner',
    name: 'Broodje Dunner',
    specialty: 'Voeding & Humor',
    badge: 'VERIFIED',
    image: '',
    followers: 0,
    posts: 0,
    bio: '',
    headerImage: '',
    specialty: '',
  },
  {
    id: 'sanne-van-lierop',
    name: 'Sanne van Lierop',
    specialty: 'Running & Coaching',
    badge: 'COACH',
    image: '',
    followers: 0,
    posts: 0,
    bio: '',
    headerImage: '',
    specialty: '',
  },
  {
    id: 'fajah-lourens',
    name: 'Fajah Lourens',
    specialty: 'Fitness & Lifestyle',
    badge: 'PRO',
    image: '',
    followers: 0,
    posts: 0,
    bio: '',
    headerImage: '',
    specialty: '',
  },
  {
    id: 'mike-vereset',
    name: 'Mike Vereset',
    specialty: 'Personal Training',
    badge: 'ELITE',
    image: '',
    followers: 0,
    posts: 0,
    bio: '',
    headerImage: '',
    specialty: '',
  },
  // Toegevoegd op verzoek
  {
    id: 'joep-rovers',
    name: 'Joep Rovers',
    specialty: '',
    badge: 'VERIFIED',
    image: '',
    followers: 0,
    posts: 0,
    bio: '',
    headerImage: '',
    specialty: '',
  },
  {
    id: 'sandra-ysbrandy',
    name: 'Sandra Ysbrandy',
    specialty: '',
    badge: 'VERIFIED',
    image: '',
    followers: 0,
    posts: 0,
    bio: '',
    headerImage: '',
    specialty: '',
  },
  {
    id: 'jani-van-loghem',
    name: 'Jani van Loghem',
    specialty: '',
    badge: 'VERIFIED',
    image: '',
    followers: 0,
    posts: 0,
    bio: '',
    headerImage: '',
    specialty: '',
  },
  {
    id: 'iris-de-goede',
    name: 'Iris de Goede',
    specialty: '',
    badge: 'VERIFIED',
    image: '',
    followers: 0,
    posts: 0,
    bio: '',
    headerImage: '',
    specialty: '',
  },
  {
    id: 'virgil-en-gia',
    name: 'Virgil & Gia',
    specialty: '',
    badge: 'VERIFIED',
    image: '',
    followers: 0,
    posts: 0,
    bio: '',
    headerImage: '',
    specialty: '',
  },
  {
    id: 'thomas-van-doorn',
    name: 'Thomas van Doorn',
    specialty: '',
    badge: 'VERIFIED',
    image: '',
    followers: 0,
    posts: 0,
    bio: '',
    headerImage: '',
    specialty: '',
  },
  {
    id: 'renee-jolet-joosten',
    name: 'Renee Jolet Joosten',
    specialty: '',
    badge: 'VERIFIED',
    image: '',
    followers: 0,
    posts: 0,
    bio: '',
    headerImage: '',
    specialty: '',
  },
  {
    id: 'merel-lindenburg',
    name: 'Merel Lindenburg',
    specialty: '',
    badge: 'VERIFIED',
    image: '',
    followers: 0,
    posts: 0,
    bio: '',
    headerImage: '',
    specialty: '',
  },
  {
    id: 'jojanneke-kant',
    name: 'Jojanneke Kant',
    specialty: '',
    badge: 'VERIFIED',
    image: '',
    followers: 0,
    posts: 0,
    bio: '',
    headerImage: '',
    specialty: '',
  },
  {
    id: 'dr-ludidi',
    name: 'Dr. Ludidi',
    specialty: '',
    badge: 'VERIFIED',
    image: '',
    followers: 0,
    posts: 0,
    bio: '',
    headerImage: '',
    specialty: '',
  },
];

export const BADGE_COLORS: Record<CreatorBadge, { background: string; text: string }> = {
  VERIFIED: { background: '#F59E0B', text: '#FFFFFF' },
  PRO: { background: '#374151', text: '#FFFFFF' },
  ELITE: { background: '#7C3AED', text: '#FFFFFF' },
  COACH: { background: '#0EA5E9', text: '#FFFFFF' },
};
