export interface NutritionMeal {
  id: string;
  title: string;
  kcal: number;
  protein: number;
  image: string;
  description: string;
  mealType: 'Ontbijt' | 'Lunch' | 'Diner' | 'Snack' | 'Pre Workout' | 'Post Workout' | 'Herstel' | 'Smoothies' | 'Shakes';
  diets: Array<'Eiwitrijk' | 'Koolhydraatarm' | 'Keto' | 'Veganistisch' | 'Vegetarisch' | 'Glutenvrij' | 'Lactosevrij'>;
  goals: Array<'Spieropbouw' | 'Vetverlies' | 'Prestatie' | 'Uithoudingsvermogen' | 'Herstel focus' | 'Lean Bulk' | 'Levensduur'>;
  macroProfiles: Array<'Eiwitrijk' | 'Koolhydraatrijk' | 'Vetarm' | 'Gebalanceerd' | 'Onder 500 KCAL' | '500 & 800 KCAL' | '800 +'>;
  timeTags: Array<'Onder 10 min' | '10 tot 20 min' | '20 tot 40 min' | 'Meal prep'>;
  budget: '€' | '€€' | '€€€';
  exclusions: Array<'Geen noten' | 'Geen Zuivel' | 'Geen Gluten' | 'Geen Soja' | 'Zout Arm'>;
}

export const NUTRITION_MEALS: NutritionMeal[] = [
  {
    id: 'salmon-avocado-bowl',
    title: 'Zalm Avocado Bowl',
    kcal: 620,
    protein: 40,
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1600&q=80',
    description: 'Rijke bowl met zalm, avocado, rijst en groenten voor sterke herstelvoeding.',
    mealType: 'Lunch',
    diets: ['Eiwitrijk', 'Glutenvrij', 'Lactosevrij'],
    goals: ['Spieropbouw', 'Herstel focus', 'Prestatie'],
    macroProfiles: ['Eiwitrijk', 'Gebalanceerd', '500 & 800 KCAL'],
    timeTags: ['20 tot 40 min', 'Meal prep'],
    budget: '€€€',
    exclusions: ['Geen Zuivel', 'Geen Gluten'],
  },
  {
    id: 'creamy-lemon-chicken',
    title: 'Citroen Kip Pan',
    kcal: 580,
    protein: 46,
    image: 'https://images.unsplash.com/photo-1625944230945-1b7dd3b949ab?auto=format&fit=crop&w=1600&q=80',
    description: 'Sappige kip met frisse citroen, kruiden en een romige saus, hoog in eiwitten.',
    mealType: 'Diner',
    diets: ['Eiwitrijk', 'Koolhydraatarm', 'Glutenvrij'],
    goals: ['Spieropbouw', 'Lean Bulk', 'Herstel focus'],
    macroProfiles: ['Eiwitrijk', 'Vetarm', '500 & 800 KCAL'],
    timeTags: ['20 tot 40 min', 'Meal prep'],
    budget: '€€',
    exclusions: ['Geen noten', 'Geen Gluten'],
  },
  {
    id: 'steak-sweet-potato',
    title: 'Steak & Zoete Aardappel',
    kcal: 710,
    protein: 52,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1600&q=80',
    description: 'Stevige krachtmaaltijd met biefstuk, zoete aardappel en greens.',
    mealType: 'Post Workout',
    diets: ['Eiwitrijk', 'Glutenvrij', 'Lactosevrij'],
    goals: ['Spieropbouw', 'Prestatie', 'Lean Bulk'],
    macroProfiles: ['Eiwitrijk', 'Koolhydraatrijk', '500 & 800 KCAL'],
    timeTags: ['20 tot 40 min', 'Meal prep'],
    budget: '€€€',
    exclusions: ['Geen Zuivel', 'Geen Gluten'],
  },
  {
    id: 'greek-yogurt-parfait',
    title: 'Yoghurt Power Parfait',
    kcal: 420,
    protein: 32,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1600&q=80',
    description: 'Griekse yoghurt met fruit, noten en zaden als snelle high-protein optie.',
    mealType: 'Snack',
    diets: ['Eiwitrijk', 'Vegetarisch'],
    goals: ['Vetverlies', 'Herstel focus', 'Levensduur'],
    macroProfiles: ['Eiwitrijk', 'Onder 500 KCAL', 'Gebalanceerd'],
    timeTags: ['Onder 10 min'],
    budget: '€€',
    exclusions: ['Geen Gluten', 'Geen Soja', 'Zout Arm'],
  },
  {
    id: 'tofu-quinoa-stirfry',
    title: 'Tofu Quinoa Wok',
    kcal: 540,
    protein: 34,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1600&q=80',
    description: 'Plantaardig gerecht met tofu, quinoa en kleurrijke groenten.',
    mealType: 'Diner',
    diets: ['Veganistisch', 'Vegetarisch', 'Lactosevrij'],
    goals: ['Uithoudingsvermogen', 'Levensduur', 'Vetverlies'],
    macroProfiles: ['Koolhydraatrijk', 'Gebalanceerd', '500 & 800 KCAL'],
    timeTags: ['20 tot 40 min', 'Meal prep'],
    budget: '€€',
    exclusions: ['Geen noten', 'Geen Zuivel', 'Geen Gluten', 'Zout Arm'],
  },
  {
    id: 'oats-protein-bowl',
    title: 'Protein Oats Bowl',
    kcal: 480,
    protein: 30,
    image: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?auto=format&fit=crop&w=1600&q=80',
    description: 'Havermout met whey, banaan en pindakaas voor langdurige energie.',
    mealType: 'Ontbijt',
    diets: ['Eiwitrijk', 'Vegetarisch'],
    goals: ['Prestatie', 'Uithoudingsvermogen', 'Spieropbouw'],
    macroProfiles: ['Eiwitrijk', 'Koolhydraatrijk', 'Onder 500 KCAL'],
    timeTags: ['10 tot 20 min', 'Meal prep'],
    budget: '€',
    exclusions: ['Zout Arm'],
  },
  {
    id: 'egg-white-veggie-wrap',
    title: 'Egg White Veggie Wrap',
    kcal: 390,
    protein: 31,
    image: 'https://images.unsplash.com/photo-1513442542250-854d436a73f2?auto=format&fit=crop&w=1600&q=80',
    description: 'Lichte wrap met eiwitrijke eiwitten en knapperige groenten.',
    mealType: 'Ontbijt',
    diets: ['Eiwitrijk', 'Lactosevrij'],
    goals: ['Vetverlies', 'Prestatie', 'Spieropbouw'],
    macroProfiles: ['Eiwitrijk', 'Vetarm', 'Onder 500 KCAL'],
    timeTags: ['10 tot 20 min'],
    budget: '€',
    exclusions: ['Geen Zuivel', 'Zout Arm'],
  },
  {
    id: 'turkey-rice-power-bowl',
    title: 'Turkey Rice Power Bowl',
    kcal: 690,
    protein: 49,
    image: 'https://images.unsplash.com/photo-1543353071-087092ec393a?auto=format&fit=crop&w=1600&q=80',
    description: 'Mager kalkoengehakt met rijst en groenten voor stevige energie.',
    mealType: 'Lunch',
    diets: ['Eiwitrijk', 'Glutenvrij', 'Lactosevrij'],
    goals: ['Spieropbouw', 'Prestatie', 'Lean Bulk'],
    macroProfiles: ['Eiwitrijk', 'Koolhydraatrijk', '500 & 800 KCAL'],
    timeTags: ['20 tot 40 min', 'Meal prep'],
    budget: '€€',
    exclusions: ['Geen Gluten', 'Geen Zuivel'],
  },
  {
    id: 'shrimp-zoodle-stirfry',
    title: 'Shrimp Zoodle Stirfry',
    kcal: 430,
    protein: 36,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=1600&q=80',
    description: 'Snelle roerbak met garnalen en courgette-noedels.',
    mealType: 'Diner',
    diets: ['Eiwitrijk', 'Koolhydraatarm', 'Glutenvrij', 'Lactosevrij'],
    goals: ['Vetverlies', 'Herstel focus', 'Prestatie'],
    macroProfiles: ['Eiwitrijk', 'Vetarm', 'Onder 500 KCAL'],
    timeTags: ['10 tot 20 min'],
    budget: '€€',
    exclusions: ['Geen Gluten', 'Geen Zuivel', 'Zout Arm'],
  },
  {
    id: 'banana-protein-shake',
    title: 'Banaan Protein Shake',
    kcal: 350,
    protein: 33,
    image: 'https://images.unsplash.com/photo-1553530666-ba11a90f7da1?auto=format&fit=crop&w=1600&q=80',
    description: 'Romige herstelshake met banaan en whey.',
    mealType: 'Shakes',
    diets: ['Eiwitrijk', 'Vegetarisch'],
    goals: ['Herstel focus', 'Spieropbouw', 'Prestatie'],
    macroProfiles: ['Eiwitrijk', 'Onder 500 KCAL', 'Gebalanceerd'],
    timeTags: ['Onder 10 min'],
    budget: '€',
    exclusions: ['Geen Gluten', 'Zout Arm'],
  },
  {
    id: 'green-detox-smoothie',
    title: 'Green Detox Smoothie',
    kcal: 280,
    protein: 18,
    image: 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?auto=format&fit=crop&w=1600&q=80',
    description: 'Frisse smoothie met spinazie, kiwi en plantaardig eiwit.',
    mealType: 'Smoothies',
    diets: ['Veganistisch', 'Vegetarisch', 'Lactosevrij', 'Glutenvrij'],
    goals: ['Vetverlies', 'Levensduur', 'Uithoudingsvermogen'],
    macroProfiles: ['Onder 500 KCAL', 'Gebalanceerd', 'Vetarm'],
    timeTags: ['Onder 10 min'],
    budget: '€',
    exclusions: ['Geen Zuivel', 'Geen Gluten', 'Geen Soja', 'Zout Arm'],
  },
  {
    id: 'beef-keto-skillet',
    title: 'Beef Keto Skillet',
    kcal: 820,
    protein: 55,
    image: 'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=1600&q=80',
    description: 'Keto pan met rundvlees, paprika en avocado.',
    mealType: 'Diner',
    diets: ['Eiwitrijk', 'Keto', 'Glutenvrij', 'Lactosevrij'],
    goals: ['Spieropbouw', 'Lean Bulk', 'Prestatie'],
    macroProfiles: ['Eiwitrijk', '800 +', 'Gebalanceerd'],
    timeTags: ['20 tot 40 min'],
    budget: '€€€',
    exclusions: ['Geen Gluten', 'Geen Zuivel'],
  },
  {
    id: 'cottage-berry-bowl',
    title: 'Cottage Berry Bowl',
    kcal: 330,
    protein: 27,
    image: 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&w=1600&q=80',
    description: 'Frisse bowl met cottage cheese en rood fruit.',
    mealType: 'Snack',
    diets: ['Eiwitrijk', 'Vegetarisch'],
    goals: ['Vetverlies', 'Herstel focus', 'Levensduur'],
    macroProfiles: ['Eiwitrijk', 'Onder 500 KCAL', 'Vetarm'],
    timeTags: ['Onder 10 min'],
    budget: '€',
    exclusions: ['Geen Gluten', 'Zout Arm'],
  },
  {
    id: 'chicken-pasta-preworkout',
    title: 'Chicken Pasta Preworkout',
    kcal: 760,
    protein: 47,
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=1600&q=80',
    description: 'Koolhydraatrijke pasta met kip voor trainingsenergie.',
    mealType: 'Pre Workout',
    diets: ['Eiwitrijk'],
    goals: ['Prestatie', 'Uithoudingsvermogen', 'Spieropbouw'],
    macroProfiles: ['Koolhydraatrijk', '500 & 800 KCAL', 'Eiwitrijk'],
    timeTags: ['20 tot 40 min', 'Meal prep'],
    budget: '€€',
    exclusions: ['Geen noten'],
  },
  {
    id: 'lentil-chili-mealprep',
    title: 'Lentil Chili Mealprep',
    kcal: 560,
    protein: 29,
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1600&q=80',
    description: 'Vullende linzenchili met bonen en groenten.',
    mealType: 'Herstel',
    diets: ['Veganistisch', 'Vegetarisch', 'Lactosevrij'],
    goals: ['Herstel focus', 'Levensduur', 'Uithoudingsvermogen'],
    macroProfiles: ['Gebalanceerd', '500 & 800 KCAL', 'Koolhydraatrijk'],
    timeTags: ['Meal prep'],
    budget: '€',
    exclusions: ['Geen Zuivel', 'Zout Arm'],
  },
  {
    id: 'salmon-rice-onigiri',
    title: 'Salmon Rice Onigiri',
    kcal: 510,
    protein: 28,
    image: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?auto=format&fit=crop&w=1600&q=80',
    description: 'Handige rijstsnack met zalm voor onderweg.',
    mealType: 'Snack',
    diets: ['Glutenvrij', 'Lactosevrij'],
    goals: ['Prestatie', 'Uithoudingsvermogen', 'Herstel focus'],
    macroProfiles: ['Koolhydraatrijk', '500 & 800 KCAL', 'Gebalanceerd'],
    timeTags: ['10 tot 20 min', 'Meal prep'],
    budget: '€€',
    exclusions: ['Geen Gluten', 'Geen Zuivel'],
  },
  {
    id: 'tofu-satay-bowl',
    title: 'Tofu Satay Bowl',
    kcal: 640,
    protein: 35,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1600&q=80',
    description: 'Tofu bowl met satay-kruiden en bruine rijst.',
    mealType: 'Lunch',
    diets: ['Veganistisch', 'Vegetarisch', 'Lactosevrij'],
    goals: ['Spieropbouw', 'Uithoudingsvermogen', 'Prestatie'],
    macroProfiles: ['Gebalanceerd', 'Eiwitrijk', '500 & 800 KCAL'],
    timeTags: ['20 tot 40 min'],
    budget: '€€',
    exclusions: ['Geen Zuivel', 'Geen Gluten', 'Zout Arm'],
  },
  {
    id: 'overnight-oats-chia',
    title: 'Overnight Oats Chia',
    kcal: 440,
    protein: 24,
    image: 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1600&q=80',
    description: 'Mealprep ontbijt met haver, chia en bessen.',
    mealType: 'Ontbijt',
    diets: ['Vegetarisch'],
    goals: ['Levensduur', 'Uithoudingsvermogen', 'Vetverlies'],
    macroProfiles: ['Onder 500 KCAL', 'Gebalanceerd', 'Koolhydraatrijk'],
    timeTags: ['Meal prep'],
    budget: '€',
    exclusions: ['Geen Soja', 'Zout Arm'],
  },
  {
    id: 'protein-pancakes-banana',
    title: 'Protein Pancakes Banaan',
    kcal: 520,
    protein: 38,
    image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=1600&q=80',
    description: 'Luchtige eiwitpannenkoeken met banaan.',
    mealType: 'Ontbijt',
    diets: ['Eiwitrijk', 'Vegetarisch'],
    goals: ['Spieropbouw', 'Prestatie', 'Lean Bulk'],
    macroProfiles: ['Eiwitrijk', '500 & 800 KCAL', 'Gebalanceerd'],
    timeTags: ['10 tot 20 min'],
    budget: '€',
    exclusions: ['Zout Arm'],
  },
  {
    id: 'tuna-bean-salad',
    title: 'Tuna Bean Salad',
    kcal: 470,
    protein: 41,
    image: 'https://images.unsplash.com/photo-1512852939750-1305098529bf?auto=format&fit=crop&w=1600&q=80',
    description: 'Eiwitrijke tonijnsalade met witte bonen.',
    mealType: 'Lunch',
    diets: ['Eiwitrijk', 'Glutenvrij', 'Lactosevrij'],
    goals: ['Vetverlies', 'Herstel focus', 'Spieropbouw'],
    macroProfiles: ['Eiwitrijk', 'Onder 500 KCAL', 'Vetarm'],
    timeTags: ['10 tot 20 min'],
    budget: '€€',
    exclusions: ['Geen Gluten', 'Geen Zuivel', 'Zout Arm'],
  },
  {
    id: 'quark-honey-walnut',
    title: 'Quark Honey Bowl',
    kcal: 360,
    protein: 29,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1600&q=80',
    description: 'Romige quark met honing en crunchy topping.',
    mealType: 'Snack',
    diets: ['Eiwitrijk', 'Vegetarisch'],
    goals: ['Herstel focus', 'Spieropbouw', 'Levensduur'],
    macroProfiles: ['Eiwitrijk', 'Onder 500 KCAL', 'Gebalanceerd'],
    timeTags: ['Onder 10 min'],
    budget: '€',
    exclusions: ['Geen Gluten'],
  },
  {
    id: 'vegan-burrito-bowl',
    title: 'Vegan Burrito Bowl',
    kcal: 670,
    protein: 27,
    image: 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?auto=format&fit=crop&w=1600&q=80',
    description: 'Bonen, rijst en salsa in een plantaardige powerbowl.',
    mealType: 'Diner',
    diets: ['Veganistisch', 'Vegetarisch', 'Lactosevrij'],
    goals: ['Uithoudingsvermogen', 'Levensduur', 'Prestatie'],
    macroProfiles: ['Koolhydraatrijk', '500 & 800 KCAL', 'Gebalanceerd'],
    timeTags: ['20 tot 40 min', 'Meal prep'],
    budget: '€',
    exclusions: ['Geen Zuivel', 'Zout Arm'],
  },
  {
    id: 'chicken-caesar-light',
    title: 'Chicken Caesar Light',
    kcal: 490,
    protein: 43,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1600&q=80',
    description: 'Lichte caesar met extra kip en minder dressing.',
    mealType: 'Lunch',
    diets: ['Eiwitrijk', 'Koolhydraatarm'],
    goals: ['Vetverlies', 'Spieropbouw', 'Herstel focus'],
    macroProfiles: ['Eiwitrijk', 'Onder 500 KCAL', 'Vetarm'],
    timeTags: ['10 tot 20 min'],
    budget: '€€',
    exclusions: ['Geen noten'],
  },
  {
    id: 'rice-cakes-peanut-banana',
    title: 'Rice Cakes Banana Stack',
    kcal: 410,
    protein: 19,
    image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1600&q=80',
    description: 'Snelle pre workout snack met rijstwafels en banaan.',
    mealType: 'Pre Workout',
    diets: ['Vegetarisch', 'Lactosevrij', 'Glutenvrij'],
    goals: ['Prestatie', 'Uithoudingsvermogen'],
    macroProfiles: ['Koolhydraatrijk', 'Onder 500 KCAL', 'Gebalanceerd'],
    timeTags: ['Onder 10 min'],
    budget: '€',
    exclusions: ['Geen Zuivel', 'Geen Gluten', 'Zout Arm'],
  },
  {
    id: 'postworkout-choco-shake',
    title: 'Post Workout Choco Shake',
    kcal: 430,
    protein: 42,
    image: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?auto=format&fit=crop&w=1600&q=80',
    description: 'Herstelshake met cacao, whey en havermout.',
    mealType: 'Post Workout',
    diets: ['Eiwitrijk', 'Vegetarisch'],
    goals: ['Herstel focus', 'Spieropbouw', 'Lean Bulk'],
    macroProfiles: ['Eiwitrijk', 'Onder 500 KCAL', 'Gebalanceerd'],
    timeTags: ['Onder 10 min'],
    budget: '€',
    exclusions: ['Geen Gluten', 'Zout Arm'],
  },
  {
    id: 'keto-omelet-avocado',
    title: 'Keto Omelet Avocado',
    kcal: 560,
    protein: 35,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1600&q=80',
    description: 'Vullende omelet met avocado en spinazie.',
    mealType: 'Ontbijt',
    diets: ['Keto', 'Eiwitrijk', 'Glutenvrij'],
    goals: ['Vetverlies', 'Herstel focus', 'Prestatie'],
    macroProfiles: ['Eiwitrijk', '500 & 800 KCAL', 'Gebalanceerd'],
    timeTags: ['10 tot 20 min'],
    budget: '€€',
    exclusions: ['Geen Gluten', 'Geen noten'],
  },
  {
    id: 'high-carb-sushi-box',
    title: 'High Carb Sushi Box',
    kcal: 790,
    protein: 34,
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=1600&q=80',
    description: 'Sushi selectie als koolhydraatrijke pre race maaltijd.',
    mealType: 'Pre Workout',
    diets: ['Lactosevrij'],
    goals: ['Prestatie', 'Uithoudingsvermogen', 'Lean Bulk'],
    macroProfiles: ['Koolhydraatrijk', '500 & 800 KCAL', 'Gebalanceerd'],
    timeTags: ['Onder 10 min'],
    budget: '€€€',
    exclusions: ['Geen Zuivel', 'Zout Arm'],
  },
  {
    id: 'tofu-miso-soup-bowl',
    title: 'Tofu Miso Soup Bowl',
    kcal: 320,
    protein: 22,
    image: 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=1600&q=80',
    description: 'Lichte soepbowl met tofu en groenten.',
    mealType: 'Herstel',
    diets: ['Veganistisch', 'Vegetarisch', 'Lactosevrij'],
    goals: ['Herstel focus', 'Levensduur', 'Vetverlies'],
    macroProfiles: ['Onder 500 KCAL', 'Vetarm', 'Gebalanceerd'],
    timeTags: ['10 tot 20 min'],
    budget: '€',
    exclusions: ['Geen Zuivel', 'Geen noten', 'Zout Arm'],
  },
  {
    id: 'beef-rice-mealprep-box',
    title: 'Beef Rice Mealprep Box',
    kcal: 840,
    protein: 58,
    image: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=1600&q=80',
    description: 'Mealprep bak met rund, rijst en broccoli.',
    mealType: 'Herstel',
    diets: ['Eiwitrijk', 'Lactosevrij'],
    goals: ['Spieropbouw', 'Lean Bulk', 'Prestatie'],
    macroProfiles: ['800 +', 'Eiwitrijk', 'Koolhydraatrijk'],
    timeTags: ['Meal prep'],
    budget: '€€€',
    exclusions: ['Geen Zuivel'],
  },
  {
    id: 'chickpea-pasta-red-sauce',
    title: 'Chickpea Pasta Rood',
    kcal: 610,
    protein: 33,
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=1600&q=80',
    description: 'Peulvruchtenpasta met tomatensaus en basilicum.',
    mealType: 'Diner',
    diets: ['Vegetarisch', 'Lactosevrij'],
    goals: ['Uithoudingsvermogen', 'Levensduur', 'Prestatie'],
    macroProfiles: ['Koolhydraatrijk', '500 & 800 KCAL', 'Gebalanceerd'],
    timeTags: ['20 tot 40 min'],
    budget: '€€',
    exclusions: ['Geen Zuivel', 'Zout Arm'],
  },
  {
    id: 'skyr-apple-cinnamon',
    title: 'Skyr Apple Cinnamon',
    kcal: 290,
    protein: 26,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1600&q=80',
    description: 'Skyr snack met appel en kaneel.',
    mealType: 'Snack',
    diets: ['Eiwitrijk', 'Vegetarisch'],
    goals: ['Vetverlies', 'Herstel focus'],
    macroProfiles: ['Onder 500 KCAL', 'Eiwitrijk', 'Vetarm'],
    timeTags: ['Onder 10 min'],
    budget: '€',
    exclusions: ['Geen Gluten', 'Zout Arm'],
  },
  {
    id: 'vegan-protein-shake-oat',
    title: 'Vegan Oat Protein Shake',
    kcal: 410,
    protein: 30,
    image: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=1600&q=80',
    description: 'Haver shake met plantaardig eiwit en cacao.',
    mealType: 'Shakes',
    diets: ['Veganistisch', 'Vegetarisch', 'Lactosevrij'],
    goals: ['Spieropbouw', 'Herstel focus', 'Prestatie'],
    macroProfiles: ['Eiwitrijk', 'Onder 500 KCAL', 'Gebalanceerd'],
    timeTags: ['Onder 10 min'],
    budget: '€',
    exclusions: ['Geen Zuivel', 'Geen Soja', 'Zout Arm'],
  },
  {
    id: 'mediterranean-chicken-bowl',
    title: 'Mediterranean Chicken Bowl',
    kcal: 640,
    protein: 44,
    image: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=1600&q=80',
    description: 'Kip, couscous en mediterrane groenten.',
    mealType: 'Lunch',
    diets: ['Eiwitrijk'],
    goals: ['Prestatie', 'Spieropbouw', 'Uithoudingsvermogen'],
    macroProfiles: ['Gebalanceerd', '500 & 800 KCAL', 'Eiwitrijk'],
    timeTags: ['20 tot 40 min', 'Meal prep'],
    budget: '€€',
    exclusions: ['Geen noten'],
  },
  {
    id: 'zucchini-feta-egg-muffins',
    title: 'Zucchini Egg Muffins',
    kcal: 340,
    protein: 28,
    image: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=1600&q=80',
    description: 'Mealprep mini omelets met courgette.',
    mealType: 'Ontbijt',
    diets: ['Eiwitrijk', 'Vegetarisch', 'Koolhydraatarm'],
    goals: ['Vetverlies', 'Herstel focus'],
    macroProfiles: ['Eiwitrijk', 'Onder 500 KCAL', 'Vetarm'],
    timeTags: ['Meal prep'],
    budget: '€',
    exclusions: ['Geen noten', 'Geen Gluten'],
  },
  {
    id: 'rice-noodle-beef-soup',
    title: 'Rice Noodle Beef Soup',
    kcal: 590,
    protein: 39,
    image: 'https://images.unsplash.com/photo-1555126634-323283e090fa?auto=format&fit=crop&w=1600&q=80',
    description: 'Warme noedelsoep met rund en kruiden.',
    mealType: 'Herstel',
    diets: ['Eiwitrijk', 'Lactosevrij'],
    goals: ['Herstel focus', 'Prestatie', 'Uithoudingsvermogen'],
    macroProfiles: ['Gebalanceerd', '500 & 800 KCAL', 'Eiwitrijk'],
    timeTags: ['20 tot 40 min'],
    budget: '€€',
    exclusions: ['Geen Zuivel', 'Zout Arm'],
  },
  {
    id: 'chia-protein-pudding',
    title: 'Chia Protein Pudding',
    kcal: 310,
    protein: 24,
    image: 'https://images.unsplash.com/photo-1539252554453-80ab65ce3586?auto=format&fit=crop&w=1600&q=80',
    description: 'Makkelijke pudding met chia en eiwit.',
    mealType: 'Snack',
    diets: ['Vegetarisch', 'Lactosevrij'],
    goals: ['Vetverlies', 'Levensduur', 'Herstel focus'],
    macroProfiles: ['Onder 500 KCAL', 'Gebalanceerd', 'Vetarm'],
    timeTags: ['Meal prep'],
    budget: '€',
    exclusions: ['Geen noten', 'Geen Zuivel', 'Geen Gluten', 'Zout Arm'],
  },
  {
    id: 'chicken-potato-traybake',
    title: 'Chicken Potato Traybake',
    kcal: 730,
    protein: 48,
    image: 'https://images.unsplash.com/photo-1514517220031-1f3bb516a6f7?auto=format&fit=crop&w=1600&q=80',
    description: 'Ovenschotel met kip, aardappel en kruiden.',
    mealType: 'Diner',
    diets: ['Eiwitrijk', 'Lactosevrij'],
    goals: ['Spieropbouw', 'Lean Bulk', 'Prestatie'],
    macroProfiles: ['500 & 800 KCAL', 'Eiwitrijk', 'Gebalanceerd'],
    timeTags: ['20 tot 40 min', 'Meal prep'],
    budget: '€€',
    exclusions: ['Geen Zuivel', 'Geen noten'],
  },
  {
    id: 'tofu-smoothie-berry',
    title: 'Tofu Berry Smoothie',
    kcal: 340,
    protein: 23,
    image: 'https://images.unsplash.com/photo-1497534446932-c925b458314e?auto=format&fit=crop&w=1600&q=80',
    description: 'Plantaardige smoothie met zijden tofu en bessen.',
    mealType: 'Smoothies',
    diets: ['Veganistisch', 'Vegetarisch', 'Lactosevrij'],
    goals: ['Herstel focus', 'Levensduur', 'Vetverlies'],
    macroProfiles: ['Onder 500 KCAL', 'Gebalanceerd', 'Eiwitrijk'],
    timeTags: ['Onder 10 min'],
    budget: '€',
    exclusions: ['Geen noten', 'Geen Zuivel', 'Geen Gluten', 'Zout Arm'],
  },
  {
    id: 'salad-niçoise-protein',
    title: 'Nicoise Protein Salad',
    kcal: 520,
    protein: 38,
    image: 'https://images.unsplash.com/photo-1512852939750-1305098529bf?auto=format&fit=crop&w=1600&q=80',
    description: 'Salade met tonijn, ei en aardappel.',
    mealType: 'Lunch',
    diets: ['Eiwitrijk', 'Glutenvrij', 'Lactosevrij'],
    goals: ['Vetverlies', 'Prestatie', 'Herstel focus'],
    macroProfiles: ['Gebalanceerd', '500 & 800 KCAL', 'Eiwitrijk'],
    timeTags: ['10 tot 20 min'],
    budget: '€€',
    exclusions: ['Geen Gluten', 'Geen Zuivel', 'Zout Arm'],
  },
  {
    id: 'tempeh-peanut-noodle',
    title: 'Tempeh Noodle Bowl',
    kcal: 780,
    protein: 37,
    image: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=1600&q=80',
    description: 'Noodle bowl met tempeh en groenten.',
    mealType: 'Post Workout',
    diets: ['Veganistisch', 'Vegetarisch', 'Lactosevrij'],
    goals: ['Prestatie', 'Uithoudingsvermogen', 'Lean Bulk'],
    macroProfiles: ['Koolhydraatrijk', '500 & 800 KCAL', 'Gebalanceerd'],
    timeTags: ['20 tot 40 min'],
    budget: '€€',
    exclusions: ['Geen Zuivel'],
  },
  {
    id: 'egg-fried-rice-light',
    title: 'Egg Fried Rice Light',
    kcal: 610,
    protein: 26,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1600&q=80',
    description: 'Snelle wokrijst met ei en groenten.',
    mealType: 'Diner',
    diets: ['Vegetarisch', 'Lactosevrij'],
    goals: ['Prestatie', 'Uithoudingsvermogen'],
    macroProfiles: ['Koolhydraatrijk', '500 & 800 KCAL', 'Gebalanceerd'],
    timeTags: ['10 tot 20 min'],
    budget: '€',
    exclusions: ['Geen Zuivel', 'Zout Arm'],
  },
  {
    id: 'coconut-yogurt-granola',
    title: 'Coconut Yogurt Granola',
    kcal: 460,
    protein: 21,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1600&q=80',
    description: 'Plantaardige yoghurt met granola en fruit.',
    mealType: 'Ontbijt',
    diets: ['Veganistisch', 'Vegetarisch', 'Lactosevrij'],
    goals: ['Levensduur', 'Vetverlies', 'Uithoudingsvermogen'],
    macroProfiles: ['Onder 500 KCAL', 'Gebalanceerd', 'Koolhydraatrijk'],
    timeTags: ['Onder 10 min'],
    budget: '€',
    exclusions: ['Geen Zuivel', 'Zout Arm'],
  },
  {
    id: 'high-protein-muffin-shake',
    title: 'Muffin Recovery Shake',
    kcal: 520,
    protein: 44,
    image: 'https://images.unsplash.com/photo-1528712306091-ed0763094c98?auto=format&fit=crop&w=1600&q=80',
    description: 'Herstelshake met extra whey en haver.',
    mealType: 'Herstel',
    diets: ['Eiwitrijk', 'Vegetarisch'],
    goals: ['Herstel focus', 'Spieropbouw', 'Lean Bulk'],
    macroProfiles: ['Eiwitrijk', '500 & 800 KCAL', 'Gebalanceerd'],
    timeTags: ['Onder 10 min'],
    budget: '€',
    exclusions: ['Zout Arm'],
  },
  {
    id: 'cod-potato-greenbeans',
    title: 'Cod Potato Greenbeans',
    kcal: 540,
    protein: 45,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=1600&q=80',
    description: 'Magere kabeljauw met aardappel en boontjes.',
    mealType: 'Diner',
    diets: ['Eiwitrijk', 'Koolhydraatarm', 'Glutenvrij', 'Lactosevrij'],
    goals: ['Vetverlies', 'Herstel focus', 'Prestatie'],
    macroProfiles: ['Eiwitrijk', '500 & 800 KCAL', 'Vetarm'],
    timeTags: ['20 tot 40 min'],
    budget: '€€€',
    exclusions: ['Geen Gluten', 'Geen Zuivel', 'Zout Arm'],
  },
  {
    id: 'avocado-turkey-sandwich',
    title: 'Avocado Turkey Sandwich',
    kcal: 600,
    protein: 39,
    image: 'https://images.unsplash.com/photo-1550507992-eb63ffee0847?auto=format&fit=crop&w=1600&q=80',
    description: 'Volkoren sandwich met kalkoen en avocado.',
    mealType: 'Lunch',
    diets: ['Eiwitrijk'],
    goals: ['Prestatie', 'Uithoudingsvermogen', 'Spieropbouw'],
    macroProfiles: ['Gebalanceerd', '500 & 800 KCAL', 'Eiwitrijk'],
    timeTags: ['10 tot 20 min'],
    budget: '€€',
    exclusions: ['Geen noten'],
  },
  {
    id: 'preworkout-date-smoothie',
    title: 'Date Boost Smoothie',
    kcal: 470,
    protein: 25,
    image: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=1600&q=80',
    description: 'Snel opneembare pre workout smoothie met dadels.',
    mealType: 'Pre Workout',
    diets: ['Vegetarisch', 'Lactosevrij', 'Glutenvrij'],
    goals: ['Prestatie', 'Uithoudingsvermogen'],
    macroProfiles: ['Koolhydraatrijk', 'Onder 500 KCAL', 'Gebalanceerd'],
    timeTags: ['Onder 10 min'],
    budget: '€',
    exclusions: ['Geen Zuivel', 'Geen Gluten', 'Geen noten', 'Zout Arm'],
  },
  {
    id: 'lean-bulk-burrito',
    title: 'Lean Bulk Burrito',
    kcal: 860,
    protein: 54,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=1600&q=80',
    description: 'Zware burrito voor massa-opbouw met kip en rijst.',
    mealType: 'Post Workout',
    diets: ['Eiwitrijk'],
    goals: ['Lean Bulk', 'Spieropbouw', 'Prestatie'],
    macroProfiles: ['800 +', 'Eiwitrijk', 'Koolhydraatrijk'],
    timeTags: ['20 tot 40 min'],
    budget: '€€',
    exclusions: ['Geen noten'],
  },
  {
    id: 'veggie-soup-low-sodium',
    title: 'Veggie Soup Low Sodium',
    kcal: 260,
    protein: 16,
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1600&q=80',
    description: 'Lichte groentesoep met weinig zout.',
    mealType: 'Herstel',
    diets: ['Veganistisch', 'Vegetarisch', 'Lactosevrij', 'Glutenvrij'],
    goals: ['Vetverlies', 'Levensduur', 'Herstel focus'],
    macroProfiles: ['Onder 500 KCAL', 'Vetarm', 'Gebalanceerd'],
    timeTags: ['20 tot 40 min', 'Meal prep'],
    budget: '€',
    exclusions: ['Geen Zuivel', 'Geen Gluten', 'Geen Soja', 'Zout Arm', 'Geen noten'],
  },
];
