
export interface PartnerBrand {
  id: string;
  name: string;
  category: string;
  group: 'Kleding' | 'Voeding' | 'Supplementen';
  summary: string;
  image: string;
  discountLabel: string;
  discountCode: string;
  offerUrl: string;
  socials?: {
    instagram?: string;
    facebook?: string;
    youtube?: string;
    website?: string;
  };
}

export const PARTNERS: PartnerBrand[] = [
    {
      id: 'muscle-meat',
      name: 'Muscle Meat',
      category: '',
      group: 'Voeding',
      summary: '',
      image: '',
      discountLabel: '',
      discountCode: '',
      offerUrl: 'https://musclemeat.nl/',
      socials: {
        instagram: 'https://www.instagram.com/musclemeatnl/',
      },
    },
  {
    id: 'myprotein',
    name: 'MyProtein',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'Performance supplementen met exclusieve DAELY-voordelen.',
    image: 'https://logo.clearbit.com/myprotein.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-MP-10',
    offerUrl: 'https://www.myprotein.com',
  },
  {
    id: 'aybl',
    name: 'Aybl',
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Premium activewear voor vrouwen. Ontdek de nieuwste collecties en samenwerkingen.',
    image: 'https://aybl.com/cdn/shop/files/AYBL_Logo_White_Transparent_200x.png',
    discountLabel: '10% korting',
    discountCode: 'DAELY-AYBL-10',
    offerUrl: 'https://www.aybl.com/',
  },
  {
    id: 'body-fit',
    name: 'Body & Fit',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'Dagelijkse basics voor herstel, massa en performance.',
    image: 'https://logo.clearbit.com/bodyandfit.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-BF-10',
    offerUrl: 'https://www.bodyandfit.com',
  },
  {
    id: 'xxl-nutrition',
    name: 'XXL Nutrition',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'Sportvoeding en stacks voor kracht en conditie.',
    image: 'https://logo.clearbit.com/xxlnutrition.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-XXL-10',
    offerUrl: 'https://xxlnutrition.com',
  },
  {
    id: 'optimum-nutrition',
    name: 'Optimum Nutrition',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'Internationale topsupplementen met DAELY-korting.',
    image: 'https://logo.clearbit.com/optimumnutrition.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-ON-10',
    offerUrl: 'https://www.optimumnutrition.com',
  },
  {
    id: 'upfront',
    name: 'Upfront',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'Nederlands merk voor transparante sportvoeding en blends.',
    image: 'https://logo.clearbit.com/upfront.nl',
    discountLabel: '10% korting',
    discountCode: 'DAELY-UPFRONT-10',
    offerUrl: 'https://upfront.nl',
  },
  {
    id: 'clean-nutrition',
    name: 'Clean Nutrition',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'Zuivere formules gericht op herstel en dagelijkse performance.',
    image: 'https://logo.clearbit.com/cleannutrition.nl',
    discountLabel: '10% korting',
    discountCode: 'DAELY-CLEAN-10',
    offerUrl: 'https://www.cleannutrition.nl',
  },
  {
    id: 'orangefit',
    name: 'Orangefit',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'Plantaardige supplementen voor kracht, energie en herstel.',
    image: 'https://logo.clearbit.com/orangefit.nl',
    discountLabel: '10% korting',
    discountCode: 'DAELY-ORANGEFIT-10',
    offerUrl: 'https://www.orangefit.nl',
  },
  {
    id: 'virtuoos',
    name: 'Virtuoos',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'Kwaliteitssupplementen met focus op topsport en gezondheid.',
    image: 'https://logo.clearbit.com/virtuoos.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-VIRTUOOS-10',
    offerUrl: 'https://www.virtuoos.com',
  },
  {
    id: 'kosso-nutrition',
    name: 'Kosso Nutrition',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'Performance-gedreven supplementen voor intensieve trainingen.',
    image: 'https://logo.clearbit.com/kossonutrition.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-KOSSO-10',
    offerUrl: 'https://kossonutrition.com',
  },
  {
    id: 'xxl-nutrition-labs',
    name: 'XXL Nutrition Labs',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'Labs-varianten en geavanceerde stacks van XXL Nutrition.',
    image: 'https://logo.clearbit.com/xxlnutrition.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-XXL-LABS-10',
    offerUrl: 'https://xxlnutrition.com',
  },
  {
    id: 'nxt-level',
    name: 'NXT Level',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'Nederlandse sportvoeding voor kracht en lean progressie.',
    image: 'https://logo.clearbit.com/nxtlevel.nl',
    discountLabel: '10% korting',
    discountCode: 'DAELY-NXT-10',
    offerUrl: 'https://nxtlevel.nl',
  },
  {
    id: 'crazy-nutrition-nl',
    name: 'Crazy Nutrition NL',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'Innovatieve supplementen met focus op spieropbouw en herstel.',
    image: 'https://logo.clearbit.com/crazynutrition.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-CRAZY-10',
    offerUrl: 'https://crazynutrition.com',
  },
  {
    id: 'bulk',
    name: 'Bulk',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'Internationale lijn van eiwitten, snacks en performance basics.',
    image: 'https://logo.clearbit.com/bulk.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-BULK-10',
    offerUrl: 'https://www.bulk.com',
  },
  {
    id: 'esn',
    name: 'ESN',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'Premium supplementen uit Duitsland voor resultaatgerichte atleten.',
    image: 'https://logo.clearbit.com/esn.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-ESN-10',
    offerUrl: 'https://www.esn.com',
  },
  {
    id: 'applied-nutrition',
    name: 'Applied Nutrition',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'Breed assortiment voor sportprestaties en dagelijkse energie.',
    image: 'https://logo.clearbit.com/appliednutrition.uk',
    discountLabel: '10% korting',
    discountCode: 'DAELY-APPLIED-10',
    offerUrl: 'https://www.appliednutrition.uk',
  },
  {
    id: 'foodspring',
    name: 'Foodspring',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'Gezonde sportvoeding en nutrition blends voor active lifestyle.',
    image: 'https://logo.clearbit.com/foodspring.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-FOODSPRING-10',
    offerUrl: 'https://www.foodspring.com',
  },
  {
    id: 'scitec-nutrition',
    name: 'Scitec Nutrition',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'Internationaal merk met klassieke en geavanceerde supplementen.',
    image: 'https://logo.clearbit.com/scitecnutrition.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-SCITEC-10',
    offerUrl: 'https://www.scitecnutrition.com',
  },
  {
    id: 'bsn',
    name: 'BSN',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'Bekende pre-workout en protein producten voor fanatieke sporters.',
    image: 'https://logo.clearbit.com/gobsn.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-BSN-10',
    offerUrl: 'https://www.gobsn.com',
  },
  {
    id: 'dymatize',
    name: 'Dymatize',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'Eiwit- en performance-oplossingen voor hypertrofie en herstel.',
    image: 'https://logo.clearbit.com/dymatize.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-DYMATIZE-10',
    offerUrl: 'https://www.dymatize.com',
  },
  {
    id: 'rule-one-proteins',
    name: 'Rule One Proteins',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'High-performance proteins en essentials voor serieuze progressie.',
    image: 'https://logo.clearbit.com/ruleoneproteins.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-R1-10',
    offerUrl: 'https://www.ruleoneproteins.com',
  },
  {
    id: 'redcon1',
    name: 'Redcon1',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'Hardcore performance supplementen voor kracht en cut-fases.',
    image: 'https://logo.clearbit.com/redcon1.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-REDCON1-10',
    offerUrl: 'https://www.redcon1.com',
  },
  {
    id: 'cellucor',
    name: 'Cellucor',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'Pre-workout en sportvoeding met focus op trainingsoutput.',
    image: 'https://logo.clearbit.com/cellucor.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-CELLUCOR-10',
    offerUrl: 'https://www.cellucor.com',
  },
  {
    id: 'ghost-lifestyle',
    name: 'Ghost Lifestyle',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'Lifestyle supplementen met unieke smaken en branding.',
    image: 'https://logo.clearbit.com/ghostlifestyle.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-GHOST-10',
    offerUrl: 'https://www.ghostlifestyle.com',
  },
  {
    id: 'muscletech',
    name: 'MuscleTech',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'Wetenschappelijk geformuleerde producten voor progressie.',
    image: 'https://logo.clearbit.com/muscletech.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-MUSCLETECH-10',
    offerUrl: 'https://www.muscletech.com',
  },
  {
    id: 'evogen',
    name: 'Evogen',
    category: 'Supplementen Partners',
    group: 'Supplementen',
    summary: 'Top-end sportvoeding ontwikkeld voor maximale performance.',
    image: 'https://logo.clearbit.com/evogen.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-EVOGEN-10',
    offerUrl: 'https://www.evogen.com',
  },
  {
    id: 'muscle-meals',
    name: 'Muscle Meals',
    category: 'Voeding Partners',
    group: 'Voeding',
    summary: 'Macro-gebalanceerde maaltijden voor spieropbouw en herstel.',
    image: 'https://logo.clearbit.com/musclemeals.nl',
    discountLabel: '10% korting',
    discountCode: 'DAELY-MM-10',
    offerUrl: 'https://www.musclemeals.nl',
  },
  {
    id: 'fitchef',
    name: 'FitChef',
    category: 'Voeding Partners',
    group: 'Voeding',
    summary: 'Verse sportmaaltijden afgestemd op jouw doelen.',
    image: 'https://logo.clearbit.com/fitchef.nl',
    discountLabel: '10% korting',
    discountCode: 'DAELY-FITCHEF-10',
    offerUrl: 'https://www.fitchef.nl',
  },
  {
    id: 'fuel-your-body',
    name: 'Fuel Your Body',
    category: 'Voeding Partners',
    group: 'Voeding',
    summary: 'Gezonde meal-prep met focus op performance en gemak.',
    image: 'https://logo.clearbit.com/fuelyourbody.nl',
    discountLabel: '10% korting',
    discountCode: 'DAELY-FYB-10',
    offerUrl: 'https://www.fuelyourbody.nl',
  },
  {
    id: 'clean-meals',
    name: 'Clean Meals',
    category: 'Voeding Partners',
    group: 'Voeding',
    summary: 'Schone ingrediënten en kant-en-klare fit meals.',
    image: 'https://logo.clearbit.com/cleanmeals.nl',
    discountLabel: '10% korting',
    discountCode: 'DAELY-CMEALS-10',
    offerUrl: 'https://www.cleanmeals.nl',
  },
  {
    id: 'prep-the-food',
    name: 'Prep The Food',
    category: 'Voeding Partners',
    group: 'Voeding',
    summary: 'Meal-prep service voor actieve sporters en drukke schema’s.',
    image: 'https://logo.clearbit.com/prepthefood.nl',
    discountLabel: '10% korting',
    discountCode: 'DAELY-PREPTHEFOOD-10',
    offerUrl: 'https://www.prepthefood.nl',
  },
  {
    id: 'be-fit-food',
    name: 'Be Fit Food',
    category: 'Voeding Partners',
    group: 'Voeding',
    summary: 'Doelgerichte maaltijden voor fit lifestyle en vetverlies.',
    image: 'https://logo.clearbit.com/befitfood.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-BEFITFOOD-10',
    offerUrl: 'https://www.befitfood.com',
  },
  {
    id: 'fresh-fitness-food',
    name: 'Fresh Fitness Food',
    category: 'Voeding Partners',
    group: 'Voeding',
    summary: 'Verse sportmaaltijden met geoptimaliseerde macro’s.',
    image: 'https://logo.clearbit.com/freshfitnessfood.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-FFF-10',
    offerUrl: 'https://www.freshfitnessfood.com',
  },
  {
    id: 'allplants',
    name: 'Allplants',
    category: 'Voeding Partners',
    group: 'Voeding',
    summary: 'Plantaardige ready meals voor clean en sustainable eten.',
    image: 'https://logo.clearbit.com/allplants.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-ALLPLANTS-10',
    offerUrl: 'https://www.allplants.com',
  },
  {
    id: 'trifecta-nutrition',
    name: 'Trifecta Nutrition',
    category: 'Voeding Partners',
    group: 'Voeding',
    summary: 'Premium meal plans voor training, herstel en body composition.',
    image: 'https://logo.clearbit.com/trifectanutrition.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-TRIFECTA-10',
    offerUrl: 'https://www.trifectanutrition.com',
  },
  {
    id: 'factor',
    name: 'Factor',
    category: 'Voeding Partners',
    group: 'Voeding',
    summary: 'Chef-made maaltijden voor gemak, energie en consistentie.',
    image: 'https://logo.clearbit.com/factor75.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-FACTOR-10',
    offerUrl: 'https://www.factor75.com',
  },
  {
    id: 'nike',
    name: 'Nike',
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Performance apparel en schoenen voor training en running.',
    image: 'https://logo.clearbit.com/nike.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-NIKE-10',
    offerUrl: 'https://www.nike.com',
  },
  {
    id: 'adidas',
    name: 'Adidas',
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Sportkleding, schoenen en essentials voor dagelijks bewegen.',
    image: 'https://logo.clearbit.com/adidas.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-ADIDAS-10',
    offerUrl: 'https://www.adidas.com',
  },
  {
    id: 'puma',
    name: 'Puma',
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Sportstyle en performance collectie met DAELY-voordeel.',
    image: 'https://logo.clearbit.com/puma.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-PUMA-10',
    offerUrl: 'https://www.puma.com',
  },
  {
    id: 'under-armour',
    name: 'Under Armour',
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Functionele training gear voor kracht en intensieve sessies.',
    image: 'https://logo.clearbit.com/underarmour.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-UA-10',
    offerUrl: 'https://www.underarmour.com',
  },
  {
    id: 'lululemon',
    name: 'Lululemon',
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Premium activewear voor training, yoga en herstel.',
    image: 'https://logo.clearbit.com/lululemon.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-LULU-10',
    offerUrl: 'https://www.lululemon.com',
  },
  {
    id: 'new-balance',
    name: 'New Balance',
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Running en lifestyle schoenen met focus op comfort.',
    image: 'https://logo.clearbit.com/newbalance.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-NB-10',
    offerUrl: 'https://www.newbalance.com',
  },
  {
    id: 'asics',
    name: 'ASICS',
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Hardloop- en performanceproducten voor uithoudingsvermogen.',
    image: 'https://logo.clearbit.com/asics.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-ASICS-10',
    offerUrl: 'https://www.asics.com',
  },
  {
    id: 'reebok',
    name: 'Reebok',
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Cross-training en heritage sneakers met sportfocus.',
    image: 'https://logo.clearbit.com/reebok.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-REEBOK-10',
    offerUrl: 'https://www.reebok.com',
  },
  {
    id: 'columbia',
    name: 'Columbia',
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Outdoor- en all-weather gear voor actieve lifestyle.',
    image: 'https://logo.clearbit.com/columbia.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-COL-10',
    offerUrl: 'https://www.columbia.com',
  },
  {
    id: 'the-north-face',
    name: 'The North Face',
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Outdoor performance kleding en schoenen voor elk seizoen.',
    image: 'https://logo.clearbit.com/thenorthface.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-TNF-10',
    offerUrl: 'https://www.thenorthface.com',
  },
  {
    id: 'patagonia',
    name: 'Patagonia',
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Duurzame outdoor kleding voor avontuur en beweging.',
    image: 'https://logo.clearbit.com/patagonia.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-PATA-10',
    offerUrl: 'https://www.patagonia.com',
  },
  {
    id: 'arcteryx',
    name: "Arc'teryx",
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Technische outdoor gear met premium performance.',
    image: 'https://logo.clearbit.com/arcteryx.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-ARC-10',
    offerUrl: 'https://arcteryx.com',
  },
  {
    id: 'fila',
    name: 'Fila',
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Sportstyle en trainingscollecties voor dagelijks gebruik.',
    image: 'https://logo.clearbit.com/fila.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-FILA-10',
    offerUrl: 'https://www.fila.com',
  },
  {
    id: 'kappa',
    name: 'Kappa',
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Teamwear en sportkleding met klassieke roots.',
    image: 'https://logo.clearbit.com/kappa.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-KAPPA-10',
    offerUrl: 'https://www.kappa.com',
  },
  {
    id: 'hummel',
    name: 'Hummel',
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Sport- en teamwear met sterke performance focus.',
    image: 'https://logo.clearbit.com/hummel.net',
    discountLabel: '10% korting',
    discountCode: 'DAELY-HUMMEL-10',
    offerUrl: 'https://www.hummel.net',
  },
  {
    id: 'umbro',
    name: 'Umbro',
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Voetbal- en trainingskleding voor indoor en outdoor.',
    image: 'https://logo.clearbit.com/umbro.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-UMBRO-10',
    offerUrl: 'https://www.umbro.com',
  },
  {
    id: 'anta',
    name: 'Anta',
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Performance footwear en activewear voor training.',
    image: 'https://logo.clearbit.com/anta.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-ANTA-10',
    offerUrl: 'https://www.anta.com',
  },
  {
    id: 'decathlon',
    name: 'Decathlon',
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Allround sportretail voor elk niveau en elke discipline.',
    image: 'https://logo.clearbit.com/decathlon.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-DEC-10',
    offerUrl: 'https://www.decathlon.com',
  },
  {
    id: 'skechers',
    name: 'Skechers',
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Comfort-first schoenen en active lifestyle collecties.',
    image: 'https://logo.clearbit.com/skechers.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-SKECHERS-10',
    offerUrl: 'https://www.skechers.com',
  },
  {
    id: 'gymshark',
    name: 'Gymshark',
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Gym- en lifestyle apparel voor kracht en hypertrofie.',
    image: 'https://logo.clearbit.com/gymshark.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-GYMSHARK-10',
    offerUrl: 'https://www.gymshark.com',
  },
  {
    id: 'on-running',
    name: 'On Running',
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Running schoenen en gear met focus op demping en snelheid.',
    image: 'https://logo.clearbit.com/on-running.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-ONRUN-10',
    offerUrl: 'https://www.on-running.com',
  },
  {
    id: 'salomon',
    name: 'Salomon',
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Trail running en outdoor performance producten.',
    image: 'https://logo.clearbit.com/salomon.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-SALOMON-10',
    offerUrl: 'https://www.salomon.com',
  },
  {
    id: 'mizuno',
    name: 'Mizuno',
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Hardloopschoenen en teamwear met Japanse precisie.',
    image: 'https://logo.clearbit.com/mizuno.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-MIZUNO-10',
    offerUrl: 'https://www.mizuno.com',
  },
  {
    id: 'brooks',
    name: 'Brooks',
    category: 'Kleding Partners',
    group: 'Kleding',
    summary: 'Running-first schoenen en kleding voor prestaties.',
    image: 'https://logo.clearbit.com/brooksrunning.com',
    discountLabel: '10% korting',
    discountCode: 'DAELY-BROOKS-10',
    offerUrl: 'https://www.brooksrunning.com',
  },
];
