export type ThemeId = 'default' | 'classic' | 'force' | 'pastelCalm' | 'retroSport' | 'saharaDune' | 'zenInk' | 'aurora' | 'ruby' | 'coralBloom' | 'marble' | 'sapphire' | 'purpleStorm' | 'volcanicAsh' | 'venom' | 'wave';

export interface AppTheme {
  id: ThemeId;
  name: string;
  // Legacy fields for backwards compatibility
  background: string;
  card: string;
  border: string;
  titleColor: string;
  subtitleColor: string;
  tabBarActive: string;
  tabBarInactive: string;
  // Full theme tokens
  colors: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    backgroundAlt: string;
    surface: string;
    surfaceAlt: string;
    card: string;
    cardSoft: string;
    text: string;
    textMuted: string;
    textInverse: string;
    border: string;
    divider: string;
    success: string;
    warning: string;
    danger: string;
    info: string;
    // Aurora text colors (Pastel Calm only)
    auroraTitle?: string;
    auroraSubtitle?: string;
    auroraHighlight?: string;
    auroraAccent?: string;
  };
  gradients: {
    appBackground: string[];
    hero: string[];
    card: string[];
    button: string[];
    progress: string[];
    // Aurora gradients (Pastel Calm only)
    aurora?: string[];
    auroraBlue?: string[];
    auroraRose?: string[];
  };
  typography: {
    headingFontFamily: string;
    bodyFontFamily: string;
    headingWeight: string;
    bodyWeight: string;
    headingLetterSpacing: number;
    bodyLetterSpacing: number;
  };
  radius: {
    sm: number;
    md: number;
    lg: number;
    xl: number;
    full: number;
  };
  shadows: {
    card: any;
    button: any;
    glow: any;
  };
  navigation: {
    tabBarBackground: string;
    tabBarActive: string;
    tabBarInactive: string;
    headerBackground: string;
    headerText: string;
  };
  buttons: {
    primaryBackground: string;
    primaryText: string;
    secondaryBackground: string;
    secondaryText: string;
    ghostText: string;
  };
  inputs: {
    background: string;
    text: string;
    placeholder: string;
    border: string;
    focusedBorder: string;
  };
  progress: {
    track: string;
    fill: string;
    glow: string;
  };
}

export const THEMES: Record<ThemeId, AppTheme> = {
  default: {
    id: 'default',
    name: 'Standaard',
    // Legacy fields
    background: '#F1F2F4',
    card: '#FFFFFF',
    border: '#E5E7EB',
    titleColor: '#0D0F1A',
    subtitleColor: '#6B7280',
    tabBarActive: '#2563EB',
    tabBarInactive: '#9CA3AF',
    // Full theme tokens
    colors: {
      primary: '#2563EB',
      secondary: '#64748B',
      accent: '#3B82F6',
      background: '#F1F2F4',
      backgroundAlt: '#E5E7EB',
      surface: '#FFFFFF',
      surfaceAlt: '#F9FAFB',
      card: '#FFFFFF',
      cardSoft: '#F8FAFC',
      text: '#0D0F1A',
      textMuted: '#6B7280',
      textInverse: '#FFFFFF',
      border: '#E5E7EB',
      divider: '#F3F4F6',
      success: '#10B981',
      warning: '#F59E0B',
      danger: '#EF4444',
      info: '#3B82F6',
      auroraTitle: undefined,
      auroraSubtitle: undefined,
      auroraHighlight: undefined,
      auroraAccent: undefined,
    },
    gradients: {
      appBackground: ['#F1F2F4', '#E5E7EB'],
      hero: ['#2563EB', '#3B82F6'],
      card: ['#FFFFFF', '#F8FAFC'],
      button: ['#2563EB', '#1D4ED8'],
      progress: ['#2563EB', '#3B82F6'],
      aurora: undefined,
      auroraBlue: undefined,
      auroraRose: undefined,
    },
    typography: {
      headingFontFamily: 'System',
      bodyFontFamily: 'System',
      headingWeight: '700',
      bodyWeight: '400',
      headingLetterSpacing: -0.5,
      bodyLetterSpacing: 0,
    },
    radius: {
      sm: 4,
      md: 8,
      lg: 12,
      xl: 16,
      full: 9999,
    },
    shadows: {
      card: { shadowColor: '#000000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 8, elevation: 2 },
      button: { shadowColor: '#000000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.15, shadowRadius: 4, elevation: 2 },
      glow: { shadowColor: '#2563EB', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.3, shadowRadius: 16, elevation: 0 },
    },
    navigation: {
      tabBarBackground: '#FFFFFF',
      tabBarActive: '#2563EB',
      tabBarInactive: '#9CA3AF',
      headerBackground: '#FFFFFF',
      headerText: '#0D0F1A',
    },
    buttons: {
      primaryBackground: '#2563EB',
      primaryText: '#FFFFFF',
      secondaryBackground: '#E5E7EB',
      secondaryText: '#0D0F1A',
      ghostText: '#2563EB',
    },
    inputs: {
      background: '#FFFFFF',
      text: '#0D0F1A',
      placeholder: '#9CA3AF',
      border: '#E5E7EB',
      focusedBorder: '#2563EB',
    },
    progress: {
      track: '#E5E7EB',
      fill: '#2563EB',
      glow: 'rgba(37, 99, 235, 0.3)',
    },
  },
  classic: {
    id: 'classic',
    name: 'DAELY CLASSIC',
    // Legacy fields
    background: '#FFFFFF',
    card: '#F8FAFC',
    border: '#E2E8F0',
    titleColor: '#0F172A',
    subtitleColor: '#475569',
    tabBarActive: '#2563EB',
    tabBarInactive: '#94A3B8',
    // Full theme tokens
    colors: {
      primary: '#2563EB',
      secondary: '#475569',
      accent: '#0EA5E9',
      background: '#FFFFFF',
      backgroundAlt: '#F8FAFC',
      surface: '#FFFFFF',
      surfaceAlt: '#F1F5F9',
      card: '#F8FAFC',
      cardSoft: '#F1F5F9',
      text: '#0F172A',
      textMuted: '#475569',
      textInverse: '#FFFFFF',
      border: '#E2E8F0',
      divider: '#F1F5F9',
      success: '#10B981',
      warning: '#F59E0B',
      danger: '#EF4444',
      info: '#0EA5E9',
      // DAELY Classic Aurora text colors
      auroraTitle: '#0F172A',
      auroraSubtitle: '#475569',
      auroraHighlight: '#2563EB',
      auroraAccent: '#0EA5E9',
    },
    gradients: {
      appBackground: ['#FFFFFF', '#F8FAFC'],
      hero: ['#2563EB', '#0EA5E9'],
      card: ['#F8FAFC', '#F1F5F9'],
      button: ['#2563EB', '#0EA5E9'],
      progress: ['#2563EB', '#0EA5E9'],
      // DAELY Classic Aurora gradients for ribbon cards
      aurora: ['#FFFFFF', '#F0F9FF', '#EFF6FF'],
      auroraBlue: ['#FFFFFF', '#F0F9FF', '#DBEAFE'],
      auroraRose: ['#FFFFFF', '#F0F9FF', '#E0F2FE'],
    },
    typography: {
      headingFontFamily: 'System',
      bodyFontFamily: 'System',
      headingWeight: '600',
      bodyWeight: '400',
      headingLetterSpacing: 0,
      bodyLetterSpacing: 0.2,
    },
    radius: {
      sm: 8,
      md: 12,
      lg: 16,
      xl: 24,
      full: 9999,
    },
    shadows: {
      card: { shadowColor: '#000000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.08, shadowRadius: 6, elevation: 1 },
      button: { shadowColor: '#000000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.12, shadowRadius: 4, elevation: 2 },
      glow: { shadowColor: '#2563EB', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.2, shadowRadius: 12, elevation: 0 },
    },
    navigation: {
      tabBarBackground: '#FFFFFF',
      tabBarActive: '#2563EB',
      tabBarInactive: '#94A3B8',
      headerBackground: '#FFFFFF',
      headerText: '#0F172A',
    },
    buttons: {
      primaryBackground: '#2563EB',
      primaryText: '#FFFFFF',
      secondaryBackground: '#E2E8F0',
      secondaryText: '#0F172A',
      ghostText: '#2563EB',
    },
    inputs: {
      background: '#FFFFFF',
      text: '#0F172A',
      placeholder: '#94A3B8',
      border: '#E2E8F0',
      focusedBorder: '#2563EB',
    },
    progress: {
      track: '#E2E8F0',
      fill: '#2563EB',
      glow: 'rgba(37, 99, 235, 0.25)',
    },
  },
  force: {
    id: 'force',
    name: 'Force',
    // Legacy fields
    background: '#FFF1F2',
    card: '#FFFFFF',
    border: '#FECACA',
    titleColor: '#7F1D1D',
    subtitleColor: '#B91C1C',
    tabBarActive: '#991B1B',
    tabBarInactive: '#FCA5A5',
    // Full theme tokens
    colors: {
      primary: '#DC2626',
      secondary: '#991B1B',
      accent: '#EF4444',
      background: '#FFF1F2',
      backgroundAlt: '#FEE2E2',
      surface: '#FFFFFF',
      surfaceAlt: '#FEF2F2',
      card: '#FFFFFF',
      cardSoft: '#FEF2F2',
      text: '#7F1D1D',
      textMuted: '#B91C1C',
      textInverse: '#FFFFFF',
      border: '#FECACA',
      divider: '#FEE2E2',
      success: '#059669',
      warning: '#D97706',
      danger: '#DC2626',
      info: '#2563EB',
      // Force Aurora text colors
      auroraTitle: '#7F1D1D',
      auroraSubtitle: '#B91C1C',
      auroraHighlight: '#EF4444',
      auroraAccent: '#DC2626',
    },
    gradients: {
      appBackground: ['#FFF1F2', '#FEE2E2'],
      hero: ['#DC2626', '#B91C1C'],
      card: ['#FFFFFF', '#FEF2F2'],
      button: ['#DC2626', '#B91C1C'],
      progress: ['#DC2626', '#EF4444'],
      // Force Aurora gradients for ribbon cards
      aurora: ['#FFFFFF', '#FFF1F2', '#FFE4E6'],
      auroraBlue: ['rgba(254, 202, 202, 0.55)', 'rgba(254, 202, 202, 0.12)'],
      auroraRose: ['rgba(239, 68, 68, 0.65)', 'rgba(239, 68, 68, 0.30)'],
    },
    typography: {
      headingFontFamily: 'System',
      bodyFontFamily: 'System',
      headingWeight: '800',
      bodyWeight: '500',
      headingLetterSpacing: -0.8,
      bodyLetterSpacing: 0.1,
    },
    radius: {
      sm: 2,
      md: 6,
      lg: 10,
      xl: 14,
      full: 9999,
    },
    shadows: {
      card: { shadowColor: '#DC2626', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.15, shadowRadius: 12, elevation: 4 },
      button: { shadowColor: '#DC2626', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.25, shadowRadius: 6, elevation: 3 },
      glow: { shadowColor: '#DC2626', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.4, shadowRadius: 20, elevation: 0 },
    },
    navigation: {
      tabBarBackground: '#FFFFFF',
      tabBarActive: '#991B1B',
      tabBarInactive: '#FCA5A5',
      headerBackground: '#FFFFFF',
      headerText: '#7F1D1D',
    },
    buttons: {
      primaryBackground: '#DC2626',
      primaryText: '#FFFFFF',
      secondaryBackground: '#FECACA',
      secondaryText: '#7F1D1D',
      ghostText: '#DC2626',
    },
    inputs: {
      background: '#FFFFFF',
      text: '#7F1D1D',
      placeholder: '#FCA5A5',
      border: '#FECACA',
      focusedBorder: '#DC2626',
    },
    progress: {
      track: '#FECACA',
      fill: '#DC2626',
      glow: 'rgba(220, 38, 38, 0.4)',
    },
  },
  pastelCalm: {
    id: 'pastelCalm',
    name: 'Pastel Calm',
    // Legacy fields
    background: '#F0EEFF',
    card: '#FFFFFF',
    border: '#C4B8F0',
    titleColor: '#4A3A8C',
    subtitleColor: '#8B7DC8',
    tabBarActive: '#4A3A8C',
    tabBarInactive: '#C4B8F0',
    // Full theme tokens
    colors: {
      primary: '#6B5B95',
      secondary: '#9B8FC7',
      accent: '#7B6BA5',
      background: '#F0EEFF',
      backgroundAlt: '#E8E6FF',
      surface: '#FFFFFF',
      surfaceAlt: '#F5F3FF',
      card: '#FFFFFF',
      cardSoft: '#F5F3FF',
      text: '#4A3A8C',
      textMuted: '#8B7DC8',
      textInverse: '#FFFFFF',
      border: '#C4B8F0',
      divider: '#DDD8FF',
      success: '#6BBF7B',
      warning: '#E8B84A',
      danger: '#E87272',
      info: '#6B9FE8',
      // Pastel Calm Aurora text colors
      auroraTitle: '#1E1B4B',
      auroraSubtitle: '#4A3A8C',
      auroraHighlight: '#6B5B95',
      auroraAccent: '#8B7CF6',
    },
    gradients: {
      appBackground: ['#F0EEFF', '#E8E6FF'],
      hero: ['#6B5B95', '#9B8FC7'],
      card: ['#FFFFFF', '#F5F3FF'],
      button: ['#6B5B95', '#5A4A84'],
      progress: ['#6B5B95', '#9B8FC7'],
      // Pastel Calm Aurora gradients for ribbon cards
      aurora: ['#E8E6FF', '#D0CCFF', '#B8B4FF'],
      auroraBlue: ['#EAF0FF', '#D7DDFF', '#C5CBFF'],
      auroraRose: ['#F3E8FF', '#DED0FF', '#C8B8FF'],
    },
    typography: {
      headingFontFamily: 'System',
      bodyFontFamily: 'System',
      headingWeight: '500',
      bodyWeight: '400',
      headingLetterSpacing: 0.5,
      bodyLetterSpacing: 0.3,
    },
    radius: {
      sm: 12,
      md: 16,
      lg: 20,
      xl: 24,
      full: 9999,
    },
    shadows: {
      card: { shadowColor: '#6B5B95', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 10, elevation: 2 },
      button: { shadowColor: '#6B5B95', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 6, elevation: 2 },
      glow: { shadowColor: '#6B5B95', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.25, shadowRadius: 18, elevation: 0 },
    },
    navigation: {
      tabBarBackground: '#FFFFFF',
      tabBarActive: '#4A3A8C',
      tabBarInactive: '#C4B8F0',
      headerBackground: '#FFFFFF',
      headerText: '#4A3A8C',
    },
    buttons: {
      primaryBackground: '#6B5B95',
      primaryText: '#FFFFFF',
      secondaryBackground: '#E8E6FF',
      secondaryText: '#4A3A8C',
      ghostText: '#6B5B95',
    },
    inputs: {
      background: '#FFFFFF',
      text: '#4A3A8C',
      placeholder: '#C4B8F0',
      border: '#C4B8F0',
      focusedBorder: '#6B5B95',
    },
    progress: {
      track: '#C4B8F0',
      fill: '#6B5B95',
      glow: 'rgba(107, 91, 149, 0.3)',
    },
  },
  retroSport: {
    id: 'retroSport',
    name: 'Retro Sport',
    // Legacy fields
    background: '#F5F0E8',
    card: '#FFFDF7',
    border: '#1B2E6B',
    titleColor: '#1B2E6B',
    subtitleColor: '#C0392B',
    tabBarActive: '#1B2E6B',
    tabBarInactive: '#E8622A',
    // Full theme tokens
    colors: {
      primary: '#1B2E6B',
      secondary: '#C0392B',
      accent: '#E8622A',
      background: '#F5F0E8',
      backgroundAlt: '#EBE5D9',
      surface: '#FFFDF7',
      surfaceAlt: '#F8F3E8',
      card: '#FFFDF7',
      cardSoft: '#F8F3E8',
      text: '#1B2E6B',
      textMuted: '#5A5A5A',
      textInverse: '#FFFFFF',
      border: '#1B2E6B',
      divider: '#D4CFC4',
      success: '#27AE60',
      warning: '#F39C12',
      danger: '#C0392B',
      info: '#2980B9',
      // Retro Sport Aurora text colors (red/blue vintage sport)
      auroraTitle: '#1B2E6B',
      auroraSubtitle: '#B42318',
      auroraHighlight: '#E8622A',
      auroraAccent: '#C0392B',
    },
    gradients: {
      appBackground: ['#F5F0E8', '#EBE5D9'],
      hero: ['#1B2E6B', '#2C3E50'],
      card: ['#FFFDF7', '#F8F3E8'],
      button: ['#1B2E6B', '#34495E'],
      progress: ['#E8622A', '#C0392B'],
      // Retro Sport Aurora gradients for ribbon cards (subtle vintage sport)
      aurora: ['#FFFDF7', '#F7F0E6', '#FBE3D0'],
      auroraBlue: ['rgba(27, 46, 107, 0.16)', 'rgba(27, 46, 107, 0.04)'],
      auroraRose: ['rgba(192, 57, 43, 0.22)', 'rgba(232, 98, 42, 0.06)'],
    },
    typography: {
      headingFontFamily: 'System',
      bodyFontFamily: 'System',
      headingWeight: '800',
      bodyWeight: '600',
      headingLetterSpacing: -1,
      bodyLetterSpacing: 0.2,
    },
    radius: {
      sm: 0,
      md: 4,
      lg: 6,
      xl: 8,
      full: 9999,
    },
    shadows: {
      card: { shadowColor: '#000000', shadowOffset: { width: 4, height: 4 }, shadowOpacity: 0.15, shadowRadius: 0, elevation: 3 },
      button: { shadowColor: '#000000', shadowOffset: { width: 3, height: 3 }, shadowOpacity: 0.2, shadowRadius: 0, elevation: 2 },
      glow: { shadowColor: '#E8622A', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.3, shadowRadius: 15, elevation: 0 },
    },
    navigation: {
      tabBarBackground: '#1B2E6B',
      tabBarActive: '#FFFFFF',
      tabBarInactive: '#E8622A',
      headerBackground: '#1B2E6B',
      headerText: '#FFFFFF',
    },
    buttons: {
      primaryBackground: '#1B2E6B',
      primaryText: '#FFFFFF',
      secondaryBackground: '#E8622A',
      secondaryText: '#FFFFFF',
      ghostText: '#1B2E6B',
    },
    inputs: {
      background: '#FFFDF7',
      text: '#1B2E6B',
      placeholder: '#9CA3AF',
      border: '#1B2E6B',
      focusedBorder: '#E8622A',
    },
    progress: {
      track: '#D4CFC4',
      fill: '#E8622A',
      glow: 'rgba(232, 98, 42, 0.35)',
    },
  },
  saharaDune: {
    id: 'saharaDune',
    name: 'Sahara Dune',
    // Legacy fields
    background: '#FDF6EC',
    card: '#FFFAF3',
    border: '#E8D0B0',
    titleColor: '#8B5A2B',
    subtitleColor: '#B8895A',
    tabBarActive: '#C89B72',
    tabBarInactive: '#D9C1A0',
    // Full theme tokens
    colors: {
      primary: '#C89B72',
      secondary: '#B8895A',
      accent: '#D4A574',
      background: '#FDF6EC',
      backgroundAlt: '#F5EAD8',
      surface: '#FFFAF3',
      surfaceAlt: '#FDF2E3',
      card: '#FFFAF3',
      cardSoft: '#FDF2E3',
      text: '#8B5A2B',
      textMuted: '#A67B5B',
      textInverse: '#FFFFFF',
      border: '#E8D0B0',
      divider: '#E8D4BC',
      success: '#8FB872',
      warning: '#D4A84A',
      danger: '#C4786A',
      info: '#7BA8C4',
      // Sahara Dune Aurora text colors (softer, warmer)
      auroraTitle: '#7A4E24',
      auroraSubtitle: '#9A6B3A',
      auroraHighlight: '#E7C99B',
      auroraAccent: '#C89B72',
    },
    gradients: {
      appBackground: ['#FDF6EC', '#F5EAD8'],
      hero: ['#C89B72', '#A67B5B'],
      card: ['#FFFAF3', '#FDF2E3'],
      button: ['#C89B72', '#A67B5B'],
      progress: ['#C89B72', '#D4A574'],
      // Sahara Dune Aurora gradients for ribbon cards (softer, less contrast)
      aurora: ['#FFFFFF', '#FDF8EF', '#F3E4CF'],
      auroraBlue: ['rgba(232, 208, 176, 0.32)', 'rgba(232, 208, 176, 0.10)'],
      auroraRose: ['rgba(212, 165, 116, 0.35)', 'rgba(212, 165, 116, 0.12)'],
    },
    typography: {
      headingFontFamily: 'System',
      bodyFontFamily: 'System',
      headingWeight: '600',
      bodyWeight: '400',
      headingLetterSpacing: 0.3,
      bodyLetterSpacing: 0.1,
    },
    radius: {
      sm: 8,
      md: 12,
      lg: 16,
      xl: 20,
      full: 9999,
    },
    shadows: {
      card: { shadowColor: '#C89B72', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.12, shadowRadius: 10, elevation: 3 },
      button: { shadowColor: '#C89B72', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.15, shadowRadius: 5, elevation: 2 },
      glow: { shadowColor: '#C89B72', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.3, shadowRadius: 16, elevation: 0 },
    },
    navigation: {
      tabBarBackground: '#FFFAF3',
      tabBarActive: '#C89B72',
      tabBarInactive: '#D9C1A0',
      headerBackground: '#FFFAF3',
      headerText: '#8B5A2B',
    },
    buttons: {
      primaryBackground: '#C89B72',
      primaryText: '#FFFFFF',
      secondaryBackground: '#E8D0B0',
      secondaryText: '#8B5A2B',
      ghostText: '#C89B72',
    },
    inputs: {
      background: '#FFFAF3',
      text: '#8B5A2B',
      placeholder: '#D9C1A0',
      border: '#E8D0B0',
      focusedBorder: '#C89B72',
    },
    progress: {
      track: '#E8D0B0',
      fill: '#C89B72',
      glow: 'rgba(200, 155, 114, 0.35)',
    },
  },
  zenInk: {
    id: 'zenInk',
    name: 'Zen Ink',
    // Legacy fields
    background: '#F5F0E8',
    card: '#2D2D2D',
    border: '#3D3D3D',
    titleColor: '#FFFFFF',
    subtitleColor: '#B0B0B0',
    tabBarActive: '#1A1A1A',
    tabBarInactive: '#6B6B6B',
    // Full theme tokens
    colors: {
      primary: '#FFFFFF',
      secondary: '#B0B0B0',
      accent: '#D0D0D0',
      background: '#F5F0E8',
      backgroundAlt: '#EBE5D9',
      surface: '#2D2D2D',
      surfaceAlt: '#252525',
      card: '#2D2D2D',
      cardSoft: '#252525',
      text: '#FFFFFF',
      textMuted: '#B0B0B0',
      textInverse: '#1A1A1A',
      border: '#3D3D3D',
      divider: '#333333',
      success: '#4ADE80',
      warning: '#FBBF24',
      danger: '#F87171',
      info: '#60A5FA',
      // Zen Ink Aurora text colors (dark premium ink)
      auroraTitle: '#FFFFFF',
      auroraSubtitle: '#B0B0B0',
      auroraHighlight: '#E5E7EB',
      auroraAccent: '#9CA3AF',
    },
    gradients: {
      appBackground: ['#F5F0E8', '#EBE5D9'],
      hero: ['#FFFFFF', '#B0B0B0'],
      card: ['#2D2D2D', '#252525'],
      button: ['#FFFFFF', '#D0D0D0'],
      progress: ['#FFFFFF', '#B0B0B0'],
      // Zen Ink Aurora gradients for ribbon cards (subtle dark ink)
      aurora: ['#111111', '#1A1A1A', '#2D2D2D'],
      auroraBlue: ['rgba(255, 255, 255, 0.10)', 'rgba(255, 255, 255, 0.03)'],
      auroraRose: ['rgba(156, 163, 175, 0.14)', 'rgba(156, 163, 175, 0.05)'],
    },
    typography: {
      headingFontFamily: 'System',
      bodyFontFamily: 'System',
      headingWeight: '300',
      bodyWeight: '300',
      headingLetterSpacing: 1,
      bodyLetterSpacing: 0.5,
    },
    radius: {
      sm: 4,
      md: 8,
      lg: 12,
      xl: 16,
      full: 9999,
    },
    shadows: {
      card: { shadowColor: '#000000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 4 },
      button: { shadowColor: '#000000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.4, shadowRadius: 4, elevation: 3 },
      glow: { shadowColor: '#FFFFFF', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.2, shadowRadius: 20, elevation: 0 },
    },
    navigation: {
      tabBarBackground: '#F5F0E8',
      tabBarActive: '#1A1A1A',
      tabBarInactive: '#6B6B6B',
      headerBackground: '#F5F0E8',
      headerText: '#1A1A1A',
    },
    buttons: {
      primaryBackground: '#FFFFFF',
      primaryText: '#1A1A1A',
      secondaryBackground: '#3D3D3D',
      secondaryText: '#FFFFFF',
      ghostText: '#FFFFFF',
    },
    inputs: {
      background: '#2D2D2D',
      text: '#FFFFFF',
      placeholder: '#6B6B6B',
      border: '#3D3D3D',
      focusedBorder: '#FFFFFF',
    },
    progress: {
      track: '#3D3D3D',
      fill: '#FFFFFF',
      glow: 'rgba(255, 255, 255, 0.25)',
    },
  },
  aurora: {
    id: 'aurora',
    name: 'Aurora',
    // Legacy fields
    background: '#0F172A',
    card: '#1E293B',
    border: '#38BDF8',
    titleColor: '#E0F2FE',
    subtitleColor: '#7DD3FC',
    tabBarActive: '#38BDF8',
    tabBarInactive: '#0EA5E9',
    // Full theme tokens
    colors: {
      primary: '#38BDF8',
      secondary: '#0EA5E9',
      accent: '#22D3EE',
      background: '#0F172A',
      backgroundAlt: '#1E293B',
      surface: '#1E293B',
      surfaceAlt: '#334155',
      card: '#1E293B',
      cardSoft: '#334155',
      text: '#E0F2FE',
      textMuted: '#7DD3FC',
      textInverse: '#0F172A',
      border: '#38BDF8',
      divider: '#1E293B',
      success: '#34D399',
      warning: '#FBBF24',
      danger: '#F87171',
      info: '#60A5FA',
      auroraTitle: undefined,
      auroraSubtitle: undefined,
      auroraHighlight: undefined,
      auroraAccent: undefined,
    },
    gradients: {
      appBackground: ['#0F172A', '#1E293B'],
      hero: ['#38BDF8', '#818CF8', '#C084FC'],
      card: ['#1E293B', '#334155'],
      button: ['#38BDF8', '#0EA5E9'],
      progress: ['#38BDF8', '#22D3EE', '#818CF8'],
      aurora: undefined,
      auroraBlue: undefined,
      auroraRose: undefined,
    },
    typography: {
      headingFontFamily: 'System',
      bodyFontFamily: 'System',
      headingWeight: '600',
      bodyWeight: '400',
      headingLetterSpacing: 0,
      bodyLetterSpacing: 0.2,
    },
    radius: {
      sm: 8,
      md: 12,
      lg: 16,
      xl: 24,
      full: 9999,
    },
    shadows: {
      card: { shadowColor: '#38BDF8', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.2, shadowRadius: 16, elevation: 4 },
      button: { shadowColor: '#38BDF8', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 3 },
      glow: { shadowColor: '#38BDF8', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.5, shadowRadius: 24, elevation: 0 },
    },
    navigation: {
      tabBarBackground: '#1E293B',
      tabBarActive: '#38BDF8',
      tabBarInactive: '#0EA5E9',
      headerBackground: '#1E293B',
      headerText: '#E0F2FE',
    },
    buttons: {
      primaryBackground: '#38BDF8',
      primaryText: '#0F172A',
      secondaryBackground: '#334155',
      secondaryText: '#E0F2FE',
      ghostText: '#38BDF8',
    },
    inputs: {
      background: '#1E293B',
      text: '#E0F2FE',
      placeholder: '#64748B',
      border: '#38BDF8',
      focusedBorder: '#22D3EE',
    },
    progress: {
      track: '#334155',
      fill: '#38BDF8',
      glow: 'rgba(56, 189, 248, 0.5)',
    },
  },
  ruby: {
    id: 'ruby',
    name: 'Ruby',
    // Legacy fields
    background: '#140607',
    card: '#2A0F16',
    border: 'rgba(244, 167, 185, 0.22)',
    titleColor: '#FFE4EC',
    subtitleColor: '#F4A7B9',
    tabBarActive: '#B8325A',
    tabBarInactive: '#5F0F2A',
    // Full theme tokens
    colors: {
      primary: '#8B1E3F',
      secondary: '#5F0F2A',
      accent: '#B8325A',
      background: '#140607',
      backgroundAlt: '#240A10',
      surface: '#2A0F16',
      surfaceAlt: '#3A1420',
      card: '#2A0F16',
      cardSoft: '#3A1420',
      text: '#FFE4EC',
      textMuted: '#F4A7B9',
      textInverse: '#140607',
      border: 'rgba(244, 167, 185, 0.22)',
      divider: 'rgba(255, 228, 236, 0.10)',
      success: '#34D399',
      warning: '#FBBF24',
      danger: '#EF4444',
      info: '#60A5FA',
      // Ruby Aurora text colors (deep burgundy/wine red)
      auroraTitle: '#FFE4EC',
      auroraSubtitle: '#F4A7B9',
      auroraHighlight: '#E45A7A',
      auroraAccent: '#B8325A',
      // Ruby custom glow tokens (subtle gemstone/wine glow)
      rubyGlowBorder: 'rgba(244, 167, 185, 0.22)',
      rubyGlowShadow: 'rgba(184, 50, 90, 0.24)',
      rubyIconBg: 'rgba(184, 50, 90, 0.14)',
      rubyIconBorder: 'rgba(244, 167, 185, 0.24)',
      rubyIconColor: '#FFE4EC',
    },
    gradients: {
      appBackground: ['#140607', '#240A10'],
      hero: ['#8B1E3F', '#B8325A', '#E45A7A'],
      card: ['#2A0F16', '#3A1420'],
      button: ['#8B1E3F', '#5F0F2A'],
      progress: ['#8B1E3F', '#B8325A', '#E45A7A'],
      // Ruby Aurora gradients for ribbon cards (subtle wine red/gemstone)
      aurora: ['#140607', '#240A10', '#3A1420'],
      auroraBlue: ['rgba(95, 15, 42, 0.28)', 'rgba(95, 15, 42, 0.08)'],
      auroraRose: ['rgba(184, 50, 90, 0.26)', 'rgba(228, 90, 122, 0.08)'],
    },
    typography: {
      headingFontFamily: 'System',
      bodyFontFamily: 'System',
      headingWeight: '600',
      bodyWeight: '400',
      headingLetterSpacing: 0,
      bodyLetterSpacing: 0.1,
    },
    radius: {
      sm: 8,
      md: 12,
      lg: 16,
      xl: 20,
      full: 9999,
    },
    shadows: {
      card: { shadowColor: '#B8325A', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.2, shadowRadius: 12, elevation: 4 },
      button: { shadowColor: '#B8325A', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.25, shadowRadius: 6, elevation: 3 },
      glow: { shadowColor: '#B8325A', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.35, shadowRadius: 20, elevation: 0 },
    },
    navigation: {
      tabBarBackground: '#2A0F16',
      tabBarActive: '#B8325A',
      tabBarInactive: '#5F0F2A',
      headerBackground: '#2A0F16',
      headerText: '#FFE4EC',
    },
    buttons: {
      primaryBackground: '#8B1E3F',
      primaryText: '#FFFFFF',
      secondaryBackground: '#3A1420',
      secondaryText: '#FFE4EC',
      ghostText: '#B8325A',
    },
    inputs: {
      background: '#2A0F16',
      text: '#FFE4EC',
      placeholder: '#5F0F2A',
      border: 'rgba(244, 167, 185, 0.22)',
      focusedBorder: '#B8325A',
    },
    progress: {
      track: '#3A1420',
      fill: '#8B1E3F',
      glow: 'rgba(139, 30, 63, 0.35)',
    },
  },
  coralBloom: {
    id: 'coralBloom',
    name: 'Coral Bloom',
    // Legacy fields
    background: '#FFF5F5',
    card: '#FFFFFF',
    border: '#FED7D7',
    titleColor: '#9B2C2C',
    subtitleColor: '#C53030',
    tabBarActive: '#E53E3E',
    tabBarInactive: '#FC8181',
    // Full theme tokens
    colors: {
      primary: '#E53E3E',
      secondary: '#C53030',
      accent: '#FC8181',
      background: '#FFF5F5',
      backgroundAlt: '#FED7D7',
      surface: '#FFFFFF',
      surfaceAlt: '#FFF5F5',
      card: '#FFFFFF',
      cardSoft: '#FFF5F5',
      text: '#9B2C2C',
      textMuted: '#C53030',
      textInverse: '#FFFFFF',
      border: '#FED7D7',
      divider: '#FEB2B2',
      success: '#48BB78',
      warning: '#ECC94B',
      danger: '#E53E3E',
      info: '#4299E1',
      auroraTitle: undefined,
      auroraSubtitle: undefined,
      auroraHighlight: undefined,
      auroraAccent: undefined,
    },
    gradients: {
      appBackground: ['#FFF5F5', '#FED7D7'],
      hero: ['#E53E3E', '#FC8181', '#FEB2B2'],
      card: ['#FFFFFF', '#FFF5F5'],
      button: ['#E53E3E', '#C53030'],
      progress: ['#E53E3E', '#FC8181'],
      aurora: undefined,
      auroraBlue: undefined,
      auroraRose: undefined,
    },
    typography: {
      headingFontFamily: 'System',
      bodyFontFamily: 'System',
      headingWeight: '600',
      bodyWeight: '400',
      headingLetterSpacing: 0.2,
      bodyLetterSpacing: 0.3,
    },
    radius: {
      sm: 10,
      md: 14,
      lg: 18,
      xl: 22,
      full: 9999,
    },
    shadows: {
      card: { shadowColor: '#E53E3E', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.12, shadowRadius: 12, elevation: 3 },
      button: { shadowColor: '#E53E3E', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.18, shadowRadius: 6, elevation: 2 },
      glow: { shadowColor: '#E53E3E', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.35, shadowRadius: 20, elevation: 0 },
    },
    navigation: {
      tabBarBackground: '#FFFFFF',
      tabBarActive: '#E53E3E',
      tabBarInactive: '#FC8181',
      headerBackground: '#FFFFFF',
      headerText: '#9B2C2C',
    },
    buttons: {
      primaryBackground: '#E53E3E',
      primaryText: '#FFFFFF',
      secondaryBackground: '#FED7D7',
      secondaryText: '#9B2C2C',
      ghostText: '#E53E3E',
    },
    inputs: {
      background: '#FFFFFF',
      text: '#9B2C2C',
      placeholder: '#FC8181',
      border: '#FED7D7',
      focusedBorder: '#E53E3E',
    },
    progress: {
      track: '#FED7D7',
      fill: '#E53E3E',
      glow: 'rgba(229, 62, 62, 0.4)',
    },
  },
  marble: {
    id: 'marble',
    name: 'Marble',
    // Legacy fields
    background: '#F7F7F7',
    card: '#FFFFFF',
    border: '#E5E5E5',
    titleColor: '#262626',
    subtitleColor: '#525252',
    tabBarActive: '#404040',
    tabBarInactive: '#A3A3A3',
    // Full theme tokens
    colors: {
      primary: '#404040',
      secondary: '#525252',
      accent: '#737373',
      background: '#F7F7F7',
      backgroundAlt: '#E5E5E5',
      surface: '#FFFFFF',
      surfaceAlt: '#FAFAFA',
      card: '#FFFFFF',
      cardSoft: '#FAFAFA',
      text: '#262626',
      textMuted: '#525252',
      textInverse: '#FFFFFF',
      border: '#E5E5E5',
      divider: '#F0F0F0',
      success: '#22C55E',
      warning: '#EAB308',
      danger: '#EF4444',
      info: '#3B82F6',
      auroraTitle: undefined,
      auroraSubtitle: undefined,
      auroraHighlight: undefined,
      auroraAccent: undefined,
    },
    gradients: {
      appBackground: ['#F7F7F7', '#E5E5E5'],
      hero: ['#404040', '#737373', '#A3A3A3'],
      card: ['#FFFFFF', '#FAFAFA'],
      button: ['#404040', '#262626'],
      progress: ['#404040', '#737373'],
      aurora: undefined,
      auroraBlue: undefined,
      auroraRose: undefined,
    },
    typography: {
      headingFontFamily: 'System',
      bodyFontFamily: 'System',
      headingWeight: '500',
      bodyWeight: '400',
      headingLetterSpacing: 0.5,
      bodyLetterSpacing: 0.2,
    },
    radius: {
      sm: 2,
      md: 4,
      lg: 6,
      xl: 8,
      full: 9999,
    },
    shadows: {
      card: { shadowColor: '#000000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 1 },
      button: { shadowColor: '#000000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.15, shadowRadius: 3, elevation: 1 },
      glow: { shadowColor: '#404040', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.2, shadowRadius: 12, elevation: 0 },
    },
    navigation: {
      tabBarBackground: '#FFFFFF',
      tabBarActive: '#404040',
      tabBarInactive: '#A3A3A3',
      headerBackground: '#FFFFFF',
      headerText: '#262626',
    },
    buttons: {
      primaryBackground: '#404040',
      primaryText: '#FFFFFF',
      secondaryBackground: '#E5E5E5',
      secondaryText: '#262626',
      ghostText: '#404040',
    },
    inputs: {
      background: '#FFFFFF',
      text: '#262626',
      placeholder: '#A3A3A3',
      border: '#E5E5E5',
      focusedBorder: '#404040',
    },
    progress: {
      track: '#E5E5E5',
      fill: '#404040',
      glow: 'rgba(64, 64, 64, 0.25)',
    },
  },
  sapphire: {
    id: 'sapphire',
    name: 'Sapphire',
    // Legacy fields
    background: '#0C1220',
    card: '#162032',
    border: '#3B82F6',
    titleColor: '#93C5FD',
    subtitleColor: '#60A5FA',
    tabBarActive: '#3B82F6',
    tabBarInactive: '#1E3A8A',
    // Full theme tokens
    colors: {
      primary: '#3B82F6',
      secondary: '#2563EB',
      accent: '#60A5FA',
      background: '#0C1220',
      backgroundAlt: '#162032',
      surface: '#162032',
      surfaceAlt: '#1E293B',
      card: '#162032',
      cardSoft: '#1E293B',
      text: '#93C5FD',
      textMuted: '#60A5FA',
      textInverse: '#0C1220',
      border: '#3B82F6',
      divider: '#1E293B',
      success: '#34D399',
      warning: '#FBBF24',
      danger: '#F87171',
      info: '#60A5FA',
      // Sapphire Aurora text colors (deep sapphire / royal blue)
      auroraTitle: '#EAF2FF',
      auroraSubtitle: '#BFDBFE',
      auroraHighlight: '#93C5FD',
      auroraAccent: '#3B82F6',
      // Sapphire custom shape tokens (faceted glass / gemstone)
      cardRadius: 14,
      cardBorderWidth: 1.5,
      iconBubbleRadius: 12,
      shortcutRadius: 12,
      filterRadius: 16,
      badgeRadius: 9999,
      // Sapphire gemstone/facet tokens (rustige edelsteen effecten)
      // Grote facetvlakken in plaats van vele kleine lijnen
      facetLarge: 'rgba(96, 165, 250, 0.10)',
      facetMedium: 'rgba(147, 197, 253, 0.07)',
      facetSmall: 'rgba(59, 130, 246, 0.05)',
      // Sapphire glow (één zachte glow, geen meerdere zones)
      sapphireGlow: 'rgba(59, 130, 246, 0.16)',
      // Sapphire glass border (subtiele rand)
      glassBorder: 'rgba(147, 197, 253, 0.20)',
      // Sapphire shadow (diepe maar subtiele schaduw)
      glassShadow: 'rgba(29, 78, 216, 0.28)',
    },
    gradients: {
      appBackground: ['#0C1220', '#162032'],
      hero: ['#3B82F6', '#1D4ED8', '#1E3A8A'],
      card: ['#06101F', '#0C1220', '#102A4C'],
      button: ['#3B82F6', '#2563EB'],
      progress: ['#3B82F6', '#60A5FA', '#93C5FD'],
      // Sapphire Aurora gradients for ribbon cards (rustige gemstone)
      aurora: ['#06101F', '#0C1220', '#102A4C'],
      auroraBlue: ['rgba(96, 165, 250, 0.10)', 'rgba(96, 165, 250, 0.03)'],
      auroraRose: ['rgba(147, 197, 253, 0.07)', 'rgba(147, 197, 253, 0.02)'],
    },
    typography: {
      headingFontFamily: 'System',
      bodyFontFamily: 'System',
      headingWeight: '600',
      bodyWeight: '400',
      headingLetterSpacing: 0,
      bodyLetterSpacing: 0.1,
    },
    radius: {
      sm: 6,
      md: 10,
      lg: 14,
      xl: 18,
      full: 9999,
    },
    shadows: {
      card: { shadowColor: '#1D4ED8', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.32, shadowRadius: 20, elevation: 5 },
      button: { shadowColor: '#3B82F6', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.42, shadowRadius: 12, elevation: 4 },
      glow: { shadowColor: '#60A5FA', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.6, shadowRadius: 32, elevation: 0 },
    },
    navigation: {
      tabBarBackground: '#162032',
      tabBarActive: '#3B82F6',
      tabBarInactive: '#1E3A8A',
      headerBackground: '#162032',
      headerText: '#93C5FD',
    },
    buttons: {
      primaryBackground: '#3B82F6',
      primaryText: '#FFFFFF',
      secondaryBackground: '#1E293B',
      secondaryText: '#93C5FD',
      ghostText: '#3B82F6',
    },
    inputs: {
      background: '#162032',
      text: '#93C5FD',
      placeholder: '#1E3A8A',
      border: '#3B82F6',
      focusedBorder: '#60A5FA',
    },
    progress: {
      track: '#1E293B',
      fill: '#3B82F6',
      glow: 'rgba(59, 130, 246, 0.5)',
    },
  },
  purpleStorm: {
    id: 'purpleStorm',
    name: 'Purple Storm',
    // Legacy fields
    background: '#1A0B2E',
    card: '#2D1B4E',
    border: '#8B5CF6',
    titleColor: '#DDD6FE',
    subtitleColor: '#A78BFA',
    tabBarActive: '#8B5CF6',
    tabBarInactive: '#6D28D9',
    // Full theme tokens
    colors: {
      primary: '#8B5CF6',
      secondary: '#7C3AED',
      accent: '#A78BFA',
      background: '#1A0B2E',
      backgroundAlt: '#2D1B4E',
      surface: '#2D1B4E',
      surfaceAlt: '#3D2B5E',
      card: '#2D1B4E',
      cardSoft: '#3D2B5E',
      text: '#DDD6FE',
      textMuted: '#A78BFA',
      textInverse: '#1A0B2E',
      border: '#8B5CF6',
      divider: '#3D2B5E',
      success: '#34D399',
      warning: '#FBBF24',
      danger: '#F87171',
      info: '#60A5FA',
      auroraTitle: undefined,
      auroraSubtitle: undefined,
      auroraHighlight: undefined,
      auroraAccent: undefined,
    },
    gradients: {
      appBackground: ['#1A0B2E', '#2D1B4E'],
      hero: ['#8B5CF6', '#7C3AED', '#6D28D9'],
      card: ['#2D1B4E', '#3D2B5E'],
      button: ['#8B5CF6', '#7C3AED'],
      progress: ['#8B5CF6', '#A78BFA', '#C4B5FD'],
      aurora: undefined,
      auroraBlue: undefined,
      auroraRose: undefined,
    },
    typography: {
      headingFontFamily: 'System',
      bodyFontFamily: 'System',
      headingWeight: '700',
      bodyWeight: '500',
      headingLetterSpacing: -0.3,
      bodyLetterSpacing: 0.1,
    },
    radius: {
      sm: 6,
      md: 10,
      lg: 14,
      xl: 18,
      full: 9999,
    },
    shadows: {
      card: { shadowColor: '#8B5CF6', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 18, elevation: 5 },
      button: { shadowColor: '#8B5CF6', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.4, shadowRadius: 8, elevation: 4 },
      glow: { shadowColor: '#8B5CF6', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.6, shadowRadius: 28, elevation: 0 },
    },
    navigation: {
      tabBarBackground: '#2D1B4E',
      tabBarActive: '#8B5CF6',
      tabBarInactive: '#6D28D9',
      headerBackground: '#2D1B4E',
      headerText: '#DDD6FE',
    },
    buttons: {
      primaryBackground: '#8B5CF6',
      primaryText: '#FFFFFF',
      secondaryBackground: '#3D2B5E',
      secondaryText: '#DDD6FE',
      ghostText: '#8B5CF6',
    },
    inputs: {
      background: '#2D1B4E',
      text: '#DDD6FE',
      placeholder: '#6D28D9',
      border: '#8B5CF6',
      focusedBorder: '#A78BFA',
    },
    progress: {
      track: '#3D2B5E',
      fill: '#8B5CF6',
      glow: 'rgba(139, 92, 246, 0.6)',
    },
  },
  volcanicAsh: {
    id: 'volcanicAsh',
    name: 'Volcanic Ash',
    // Legacy fields
    background: '#1C1917',
    card: '#292524',
    border: '#78716C',
    titleColor: '#E7E5E4',
    subtitleColor: '#A8A29E',
    tabBarActive: '#D6D3D1',
    tabBarInactive: '#57534E',
    // Full theme tokens
    colors: {
      primary: '#D6D3D1',
      secondary: '#A8A29E',
      accent: '#E7E5E4',
      background: '#1C1917',
      backgroundAlt: '#292524',
      surface: '#292524',
      surfaceAlt: '#44403C',
      card: '#292524',
      cardSoft: '#44403C',
      text: '#E7E5E4',
      textMuted: '#A8A29E',
      textInverse: '#1C1917',
      border: '#78716C',
      divider: '#44403C',
      success: '#34D399',
      warning: '#FBBF24',
      danger: '#F87171',
      info: '#60A5FA',
      auroraTitle: undefined,
      auroraSubtitle: undefined,
      auroraHighlight: undefined,
      auroraAccent: undefined,
    },
    gradients: {
      appBackground: ['#1C1917', '#292524'],
      hero: ['#D6D3D1', '#A8A29E', '#78716C'],
      card: ['#292524', '#44403C'],
      button: ['#D6D3D1', '#A8A29E'],
      progress: ['#D6D3D1', '#E7E5E4'],
      aurora: undefined,
      auroraBlue: undefined,
      auroraRose: undefined,
    },
    typography: {
      headingFontFamily: 'System',
      bodyFontFamily: 'System',
      headingWeight: '400',
      bodyWeight: '300',
      headingLetterSpacing: 0.8,
      bodyLetterSpacing: 0.4,
    },
    radius: {
      sm: 4,
      md: 8,
      lg: 12,
      xl: 16,
      full: 9999,
    },
    shadows: {
      card: { shadowColor: '#000000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.4, shadowRadius: 10, elevation: 4 },
      button: { shadowColor: '#000000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.5, shadowRadius: 5, elevation: 3 },
      glow: { shadowColor: '#D6D3D1', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.3, shadowRadius: 20, elevation: 0 },
    },
    navigation: {
      tabBarBackground: '#292524',
      tabBarActive: '#D6D3D1',
      tabBarInactive: '#57534E',
      headerBackground: '#292524',
      headerText: '#E7E5E4',
    },
    buttons: {
      primaryBackground: '#D6D3D1',
      primaryText: '#1C1917',
      secondaryBackground: '#44403C',
      secondaryText: '#E7E5E4',
      ghostText: '#D6D3D1',
    },
    inputs: {
      background: '#292524',
      text: '#E7E5E4',
      placeholder: '#57534E',
      border: '#78716C',
      focusedBorder: '#D6D3D1',
    },
    progress: {
      track: '#44403C',
      fill: '#D6D3D1',
      glow: 'rgba(214, 211, 209, 0.35)',
    },
  },
  venom: {
    id: 'venom',
    name: 'Venom',
    // Legacy fields
    background: '#022C22',
    card: '#064E3B',
    border: '#10B981',
    titleColor: '#6EE7B7',
    subtitleColor: '#34D399',
    tabBarActive: '#10B981',
    tabBarInactive: '#065F46',
    // Full theme tokens
    colors: {
      primary: '#10B981',
      secondary: '#059669',
      accent: '#34D399',
      background: '#022C22',
      backgroundAlt: '#064E3B',
      surface: '#064E3B',
      surfaceAlt: '#065F46',
      card: '#064E3B',
      cardSoft: '#065F46',
      text: '#6EE7B7',
      textMuted: '#34D399',
      textInverse: '#022C22',
      border: '#10B981',
      divider: '#065F46',
      success: '#34D399',
      warning: '#FBBF24',
      danger: '#F87171',
      info: '#60A5FA',
      auroraTitle: undefined,
      auroraSubtitle: undefined,
      auroraHighlight: undefined,
      auroraAccent: undefined,
    },
    gradients: {
      appBackground: ['#022C22', '#064E3B'],
      hero: ['#10B981', '#059669', '#047857'],
      card: ['#064E3B', '#065F46'],
      button: ['#10B981', '#059669'],
      progress: ['#10B981', '#34D399', '#6EE7B7'],
      aurora: undefined,
      auroraBlue: undefined,
      auroraRose: undefined,
    },
    typography: {
      headingFontFamily: 'System',
      bodyFontFamily: 'System',
      headingWeight: '700',
      bodyWeight: '500',
      headingLetterSpacing: -0.5,
      bodyLetterSpacing: 0.1,
    },
    radius: {
      sm: 4,
      md: 8,
      lg: 12,
      xl: 16,
      full: 9999,
    },
    shadows: {
      card: { shadowColor: '#10B981', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.35, shadowRadius: 16, elevation: 5 },
      button: { shadowColor: '#10B981', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.45, shadowRadius: 8, elevation: 4 },
      glow: { shadowColor: '#10B981', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.6, shadowRadius: 28, elevation: 0 },
    },
    navigation: {
      tabBarBackground: '#064E3B',
      tabBarActive: '#10B981',
      tabBarInactive: '#065F46',
      headerBackground: '#064E3B',
      headerText: '#6EE7B7',
    },
    buttons: {
      primaryBackground: '#10B981',
      primaryText: '#022C22',
      secondaryBackground: '#065F46',
      secondaryText: '#6EE7B7',
      ghostText: '#10B981',
    },
    inputs: {
      background: '#064E3B',
      text: '#6EE7B7',
      placeholder: '#065F46',
      border: '#10B981',
      focusedBorder: '#34D399',
    },
    progress: {
      track: '#065F46',
      fill: '#10B981',
      glow: 'rgba(16, 185, 129, 0.6)',
    },
  },
  wave: {
    id: 'wave',
    name: 'Wave',
    // Legacy fields
    background: '#F0F9FF',
    card: '#FFFFFF',
    border: '#7DD3FC',
    titleColor: '#0369A1',
    subtitleColor: '#0284C7',
    tabBarActive: '#0EA5E9',
    tabBarInactive: '#7DD3FC',
    // Full theme tokens
    colors: {
      primary: '#0EA5E9',
      secondary: '#0284C7',
      accent: '#38BDF8',
      background: '#F0F9FF',
      backgroundAlt: '#E0F2FE',
      surface: '#FFFFFF',
      surfaceAlt: '#F0F9FF',
      card: '#FFFFFF',
      cardSoft: '#F0F9FF',
      text: '#0369A1',
      textMuted: '#0284C7',
      textInverse: '#FFFFFF',
      border: '#7DD3FC',
      divider: '#BAE6FD',
      success: '#10B981',
      warning: '#F59E0B',
      danger: '#EF4444',
      info: '#0EA5E9',
      auroraTitle: undefined,
      auroraSubtitle: undefined,
      auroraHighlight: undefined,
      auroraAccent: undefined,
    },
    gradients: {
      appBackground: ['#F0F9FF', '#E0F2FE'],
      hero: ['#0EA5E9', '#38BDF8', '#7DD3FC'],
      card: ['#FFFFFF', '#F0F9FF'],
      button: ['#0EA5E9', '#0284C7'],
      progress: ['#0EA5E9', '#38BDF8'],
      aurora: undefined,
      auroraBlue: undefined,
      auroraRose: undefined,
    },
    typography: {
      headingFontFamily: 'System',
      bodyFontFamily: 'System',
      headingWeight: '600',
      bodyWeight: '400',
      headingLetterSpacing: 0.1,
      bodyLetterSpacing: 0.2,
    },
    radius: {
      sm: 12,
      md: 16,
      lg: 20,
      xl: 24,
      full: 9999,
    },
    shadows: {
      card: { shadowColor: '#0EA5E9', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.15, shadowRadius: 14, elevation: 3 },
      button: { shadowColor: '#0EA5E9', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 6, elevation: 2 },
      glow: { shadowColor: '#0EA5E9', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.4, shadowRadius: 22, elevation: 0 },
    },
    navigation: {
      tabBarBackground: '#FFFFFF',
      tabBarActive: '#0EA5E9',
      tabBarInactive: '#7DD3FC',
      headerBackground: '#FFFFFF',
      headerText: '#0369A1',
    },
    buttons: {
      primaryBackground: '#0EA5E9',
      primaryText: '#FFFFFF',
      secondaryBackground: '#E0F2FE',
      secondaryText: '#0369A1',
      ghostText: '#0EA5E9',
    },
    inputs: {
      background: '#FFFFFF',
      text: '#0369A1',
      placeholder: '#7DD3FC',
      border: '#7DD3FC',
      focusedBorder: '#0EA5E9',
    },
    progress: {
      track: '#E0F2FE',
      fill: '#0EA5E9',
      glow: 'rgba(14, 165, 233, 0.45)',
    },
  },
};
