export type ThemeId = 'default' | 'classic' | 'zen-ink' | 'forest-breath' | 'force' | 'pure-luxury' | 'innovation' | 'pastel-calm' | 'retro-sport' | 'pulse' | 'rogue' | 'dune' | 'ember';

export interface AppTheme {
  id: ThemeId;
  name: string;
  background: string;
  card: string;
  border: string;
  titleColor: string;
  subtitleColor: string;
  tabBarActive: string;
  tabBarInactive: string;
}

export const THEMES: Record<ThemeId, AppTheme> = {
  default: {
    id: 'default',
    name: 'Standaard',
    background: '#F1F2F4',
    card: '#FFFFFF',
    border: '#E5E7EB',
    titleColor: '#0D0F1A',
    subtitleColor: '#6B7280',
    tabBarActive: '#2563EB',
    tabBarInactive: '#9CA3AF',
  },
  classic: {
    id: 'classic',
    name: 'DAELY Classic',
    background: '#FFFFFF',
    card: '#F8FAFC',
    border: '#E5E7EB',
    titleColor: '#0D0F1A',
    subtitleColor: '#6B7280',
    tabBarActive: '#1D4ED8',
    tabBarInactive: '#93C5FD',
  },
  'zen-ink': {
    id: 'zen-ink',
    name: 'Zen Ink',
    background: '#1A1A1A',
    card: '#2D2D2D',
    border: '#3D3D3D',
    titleColor: '#FFFFFF',
    subtitleColor: '#B0B0B0',
    tabBarActive: '#FFFFFF',
    tabBarInactive: '#6B6B6B',
  },
  'forest-breath': {
    id: 'forest-breath',
    name: 'Forest Breath',
    background: '#EEF7F0',
    card: '#FFFFFF',
    border: '#CFE6D6',
    titleColor: '#0D5B35',
    subtitleColor: '#5E8A6D',
    tabBarActive: '#0D5B35',
    tabBarInactive: '#8FC9A0',
  },
  force: {
    id: 'force',
    name: 'Force',
    background: '#FFF1F2',
    card: '#FFFFFF',
    border: '#FECACA',
    titleColor: '#7F1D1D',
    subtitleColor: '#B91C1C',
    tabBarActive: '#991B1B',
    tabBarInactive: '#FCA5A5',
  },
  'pure-luxury': {
    id: 'pure-luxury',
    name: 'Pure Luxury',
    background: '#0D0D0D',
    card: '#1A1A1A',
    border: '#C9A84C',
    titleColor: '#E8C97A',
    subtitleColor: '#A07830',
    tabBarActive: '#E8C97A',
    tabBarInactive: '#5A4A20',
  },
  innovation: {
    id: 'innovation',
    name: 'Innovation',
    background: '#0A0F1E',
    card: '#111827',
    border: '#00F5A0',
    titleColor: '#E0FFF5',
    subtitleColor: '#00C97A',
    tabBarActive: '#00F5A0',
    tabBarInactive: '#1A4D3A',
  },
  'pastel-calm': {
    id: 'pastel-calm',
    name: 'Pastel Calm',
    background: '#F0EEFF',
    card: '#FFFFFF',
    border: '#C4B8F0',
    titleColor: '#4A3A8C',
    subtitleColor: '#8B7DC8',
    tabBarActive: '#4A3A8C',
    tabBarInactive: '#C4B8F0',
  },
  'retro-sport': {
    id: 'retro-sport',
    name: 'Retro Sport',
    background: '#F5F0E8',
    card: '#FFFDF7',
    border: '#1B2E6B',
    titleColor: '#1B2E6B',
    subtitleColor: '#C0392B',
    tabBarActive: '#1B2E6B',
    tabBarInactive: '#E8622A',
  },
  pulse: {
    id: 'pulse',
    name: 'Pulse',
    background: '#0A1A00',
    card: '#111F00',
    border: '#7FFF00',
    titleColor: '#ADFF2F',
    subtitleColor: '#5DBB00',
    tabBarActive: '#7FFF00',
    tabBarInactive: '#2A4A00',
  },
  rogue: {
    id: 'rogue',
    name: 'Rogue',
    background: '#0D0A00',
    card: '#1A1200',
    border: '#FF6A00',
    titleColor: '#FFB347',
    subtitleColor: '#CC5200',
    tabBarActive: '#FF6A00',
    tabBarInactive: '#4A2600',
  },
  dune: {
    id: 'dune',
    name: 'Sahara Dune',
    background: '#FDF6EC',
    card: '#FFFAF3',
    border: '#E8D0B0',
    titleColor: '#8B5A2B',
    subtitleColor: '#B8895A',
    tabBarActive: '#C89B72',
    tabBarInactive: '#D9C1A0',
  },
  ember: {
    id: 'ember',
    name: 'Ember',
    background: '#0A0500',
    card: '#150900',
    border: '#FF6A00',
    titleColor: '#FFD700',
    subtitleColor: '#FF8C00',
    tabBarActive: '#FF8C00',
    tabBarInactive: '#3A2200',
  },
};
