export type TodayQuote = {
  id: string;
  text: string;
  author?: string;
  category: 'general' | 'discipline' | 'mindset' | 'recovery' | 'performance' | 'nutrition' | 'community';
  sourceType: 'daely_original' | 'athlete' | 'coach' | 'public_person' | 'brand';
  status: 'safe' | 'needs_verification' | 'licensed';
};

export const TODAY_QUOTES: TodayQuote[] = [
  {
    id: '1',
    text: 'Vandaag hoeft niet perfect te zijn. Wel bewust, actief en beter dan gisteren.',
    category: 'mindset',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '2',
    text: 'Kleine keuzes bouwen grote progressie.',
    category: 'discipline',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '3',
    text: 'Train slim, herstel goed, blijf bouwen.',
    category: 'performance',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '4',
    text: 'Je hoeft niet alles te doen. Wel het juiste.',
    category: 'mindset',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '5',
    text: 'Elke dag telt, ook de rustige.',
    category: 'general',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '6',
    text: 'Progressie begint met verschijnen.',
    category: 'discipline',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '7',
    text: 'Vandaag is een nieuwe kans om ritme te bouwen.',
    category: 'mindset',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '8',
    text: 'Sterker worden begint met consistent blijven.',
    category: 'discipline',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '9',
    text: 'Win vandaag op discipline, niet op motivatie.',
    category: 'mindset',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '10',
    text: 'Rust is geen pauze van progressie. Het is onderdeel ervan.',
    category: 'recovery',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '11',
    text: 'Focus op het proces, niet alleen op het resultaat.',
    category: 'mindset',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '12',
    text: 'Een slechte dag is geen slechte leven.',
    category: 'mindset',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '13',
    text: 'Bouw kracht voor het moment dat je het nodig hebt.',
    category: 'performance',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '14',
    text: 'Succes is de som van kleine inspanningen, herhaald dag in dag uit.',
    category: 'discipline',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '15',
    text: 'Je lichaam is je thuis. Behandel het met respect.',
    category: 'recovery',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '16',
    text: 'Geduld is niet wachten. Geduld is blijven werken terwijl je wacht.',
    category: 'mindset',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '17',
    text: 'De enige slechte workout is degene die je niet doet.',
    category: 'discipline',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '18',
    text: 'Energie komt van actie, niet van denken.',
    category: 'performance',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '19',
    text: 'Start waar je bent, met wat je hebt.',
    category: 'mindset',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '20',
    text: 'Consistentie wint van intensiteit.',
    category: 'discipline',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '21',
    text: 'Vandaag is de dag om jezelf te zijn, niet om iemand anders.',
    category: 'mindset',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '22',
    text: 'Je kunt niet terug in de tijd, maar je kunt opnieuw beginnen.',
    category: 'mindset',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '23',
    text: 'Groei gebeurt buiten je comfortzone.',
    category: 'performance',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '24',
    text: 'Een goede routine is beter dan een goede training.',
    category: 'discipline',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '25',
    text: 'Luister naar je lichaam. Het vertelt je wat je nodig hebt.',
    category: 'recovery',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '26',
    text: 'Focus op wat je kunt controleren, niet op wat je niet kunt.',
    category: 'mindset',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '27',
    text: 'Resultaten volgen gewoontes, niet motivatie.',
    category: 'discipline',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '28',
    text: 'Je bent sterker dan je denkt.',
    category: 'mindset',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '29',
    text: 'Vandaag is een kans om beter te worden dan gisteren.',
    category: 'general',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '30',
    text: 'Bouw je dag rond gewoontes die je vooruit helpen.',
    category: 'discipline',
    sourceType: 'daely_original',
    status: 'safe',
  },
  {
    id: '31',
    text: 'Discipline is doing what needs to be done, even if you don\'t want to do it.',
    author: 'Anonymous',
    category: 'discipline',
    sourceType: 'public_person',
    status: 'safe',
  },
  {
    id: '32',
    text: 'Don\'t quit. Suffer now and live the rest of your life as a champion.',
    author: 'Muhammad Ali',
    category: 'mindset',
    sourceType: 'athlete',
    status: 'safe',
  },
  {
    id: '33',
    text: 'Inspiration is a guest that does not willingly visit the lazy.',
    author: 'Pyotr Ilyich Tchaikovsky',
    category: 'mindset',
    sourceType: 'public_person',
    status: 'safe',
  },
  {
    id: '34',
    text: 'We must all suffer one of two things: the pain of discipline or the pain of regret.',
    author: 'Jim Rohn',
    category: 'mindset',
    sourceType: 'public_person',
    status: 'safe',
  },
  {
    id: '35',
    text: 'Discipline is the bridge between goals and accomplishment.',
    author: 'Jim Rohn',
    category: 'discipline',
    sourceType: 'public_person',
    status: 'safe',
  },
  {
    id: '36',
    text: 'The only bad workout is the one that didn\'t happen.',
    author: 'Kai Greene',
    category: 'discipline',
    sourceType: 'athlete',
    status: 'safe',
  },
  {
    id: '37',
    text: 'If it doesn\'t challenge you, it won\'t change you.',
    author: 'Fred Devito',
    category: 'performance',
    sourceType: 'athlete',
    status: 'safe',
  },
  {
    id: '38',
    text: 'The successful warrior is the average man, with laser-like focus.',
    author: 'Bruce Lee',
    category: 'performance',
    sourceType: 'athlete',
    status: 'safe',
  },
  {
    id: '39',
    text: 'Success isn\'t always about greatness. It\'s about consistency.',
    author: 'Dwayne Johnson',
    category: 'discipline',
    sourceType: 'athlete',
    status: 'safe',
  },
  {
    id: '40',
    text: 'You miss 100% of the shots you don\'t take.',
    author: 'Wayne Gretzky',
    category: 'performance',
    sourceType: 'athlete',
    status: 'safe',
  },
  {
    id: '41',
    text: 'I\'ve failed over and over again in my life. That is why I succeed.',
    author: 'Michael Jordan',
    category: 'mindset',
    sourceType: 'athlete',
    status: 'safe',
  },
  {
    id: '42',
    text: 'Hard work beats talent when talent doesn\'t work hard.',
    author: 'Tim Notke',
    category: 'discipline',
    sourceType: 'public_person',
    status: 'safe',
  },
  {
    id: '43',
    text: 'Talent is natural. Skill is built by hours and hours of work.',
    author: 'Will Smith',
    category: 'performance',
    sourceType: 'athlete',
    status: 'safe',
  },
  {
    id: '44',
    text: 'Today I will do what others won\'t, so tomorrow I can do what others can\'t.',
    author: 'Jerry Rice',
    category: 'discipline',
    sourceType: 'athlete',
    status: 'safe',
  },
  {
    id: '45',
    text: 'Gold medals are made of sweat, determination and guts.',
    author: 'Dan Gable',
    category: 'performance',
    sourceType: 'athlete',
    status: 'safe',
  },
  {
    id: '46',
    text: 'There are no limits. There are only plateaus. Go beyond them.',
    author: 'Bruce Lee',
    category: 'performance',
    sourceType: 'athlete',
    status: 'safe',
  },
  {
    id: '47',
    text: 'The last reps are what make the muscle grow.',
    author: 'Arnold Schwarzenegger',
    category: 'performance',
    sourceType: 'athlete',
    status: 'safe',
  },
  {
    id: '48',
    text: 'Strength comes from struggle and the decision not to surrender.',
    author: 'Arnold Schwarzenegger',
    category: 'mindset',
    sourceType: 'athlete',
    status: 'safe',
  },
  {
    id: '49',
    text: 'Everybody wants to be a bodybuilder, but nobody wants to lift heavy weights.',
    author: 'Ronnie Coleman',
    category: 'discipline',
    sourceType: 'athlete',
    status: 'safe',
  },
  {
    id: '50',
    text: 'If you want something you\'ve never had, do something you\'ve never done.',
    author: 'Unknown',
    category: 'mindset',
    sourceType: 'public_person',
    status: 'safe',
  },
  {
    id: '51',
    text: 'A champion sees the big picture: daily hard work and thriving on challenge.',
    author: 'Summer Sanders',
    category: 'performance',
    sourceType: 'athlete',
    status: 'safe',
  },
  {
    id: '52',
    text: 'Your body can stand almost anything. It\'s your mind you have to convince.',
    author: 'Unknown',
    category: 'mindset',
    sourceType: 'public_person',
    status: 'safe',
  },
  {
    id: '53',
    text: 'Exercise is labor without weariness.',
    author: 'Samuel Johnson',
    category: 'performance',
    sourceType: 'public_person',
    status: 'safe',
  },
  {
    id: '54',
    text: 'You have to expect things of yourself before you can do them.',
    author: 'Michael Jordan',
    category: 'mindset',
    sourceType: 'athlete',
    status: 'safe',
  },
  {
    id: '55',
    text: 'If you\'re ready, you don\'t have to get ready.',
    author: 'Floyd Mayweather',
    category: 'performance',
    sourceType: 'athlete',
    status: 'safe',
  },
  {
    id: '56',
    text: 'Champions keep playing until they get it right.',
    author: 'Billie Jean King',
    category: 'discipline',
    sourceType: 'athlete',
    status: 'safe',
  },
  {
    id: '57',
    text: 'It\'s not whether you get knocked down; it\'s whether you get up.',
    author: 'Vince Lombardi',
    category: 'mindset',
    sourceType: 'coach',
    status: 'safe',
  },
  {
    id: '58',
    text: 'Believe you can and you\'re halfway there.',
    author: 'Theodore Roosevelt',
    category: 'mindset',
    sourceType: 'public_person',
    status: 'safe',
  },
  {
    id: '59',
    text: 'The only way to prove that you\'re a good sport is to lose.',
    author: 'Ernie Banks',
    category: 'mindset',
    sourceType: 'athlete',
    status: 'safe',
  },
  {
    id: '60',
    text: 'Set your goals high, and don\'t stop till you get there.',
    author: 'Bo Jackson',
    category: 'discipline',
    sourceType: 'athlete',
    status: 'safe',
  },
  {
    id: '61',
    text: 'Persistence can change failure into extraordinary achievement.',
    author: 'Marv Levy',
    category: 'discipline',
    sourceType: 'coach',
    status: 'safe',
  },
  {
    id: '62',
    text: 'Run with hope in your heart and dreams in your head.',
    author: 'Emil Zátopek',
    category: 'performance',
    sourceType: 'athlete',
    status: 'safe',
  },
];

// Placeholder voor bekende quotes (niet live gebruiken)
export const KNOWN_QUOTES_PENDING_VERIFICATION: TodayQuote[] = [];